### ISSUE TITLE
<Shift+t> <Control+t> Does not work

### ISSUE THREAD

**Issue by StefanoBelloni** [cgdb/cgdb#102]
Hallo,
I have tried the new .cpp version.
In order to compile with the compiler **clang** I forked this [repository:](https://github.com/StefanoBelloni/cgdb).
I have still one problem: on both the versions, one compiled with `g++/gcc` and one with `clang/clang++` when I press **<Shift+t>** or **<Control+t>** the input/output window (_tty_) does not open as it used to in the plain `c`-version.
All the best
Stefano.

**Comment by brasko** [comment]
I remove the feature from master.

It was never really a good solution. The documentation should show this to
you as well.

Do you use this feature often?

Thanks,
Bob Rossi

**Comment by StefanoBelloni** [comment]
Sorry, I read the old manual on the web-page.
I found it nice and useful since one dose not need to attach to a running process: for simple programs with elementary inputs/outputs is comfortable to have a small _tty_ on the same _window_ to easily give inputs and read outputs.
Thanks,
Stefano.

**Comment by brasko** [comment]
Yeah, I agree. The reason I pulled it is because it was so feature
incomplete.

I'm thinking of new ideas and will be working on something to replace this
functionality.

**Comment by brasko** [comment]
Let me know if I should reopen this issue. Hopefully the explanation is satisfactory.

**Comment by lonAlpha** [comment]
I like TTY window very much. The only issue is that newline is shown as as an uppercased E.
