### ISSUE TITLE
cgdb under tmux session doesn't update source code

### ISSUE THREAD

**Issue by abhiravk** [cgdb/cgdb#111]
During a live debugging session, stepping through the program doesn't correctly update source code (current line). The source code window show some garbage text. CTRL + L in source window fixes the source code window and current location. 
Annoying thing is that CTRL + L has to be pressed to reflect the currently executing line/pointer after each (gdb) next command. 
This problem only happens when cgdb is being executed inside tmux session.

I can confirm that this problem doesn't happen in gnome-terminal (without tmux).

**Comment by brasko** [comment]
Is this using cgdb built from master? or the last known release 0.6.8?

**Comment by abhiravk** [comment]
this issue appears in both master as well as stable release.
It even appears in the other popular clones of cgdb on github.

**Comment by brasko** [comment]
Is the program being debugged writing to the terminal window?

If you start your program in one terminal, and attach to it from another
with cgdb,
do you still have that same behavior?

**Comment by abhiravk** [comment]
to be clear I am using gdbserver and remote debugging over ssh.
the same setup works fine if tmux is not used.

**Comment by mikesart** [comment]
What is your TERM envvar set to? If you set it to:
    export TERM=screen-256color
does it work?

**Comment by mikesart** [comment]
tmux frequently asked questions
https://raw.githubusercontent.com/tmux/tmux/master/FAQ

Specifically, the below section. I use tmux all the time with cgdb and it works great if TERM is set correctly. Thanks abhiravk.

```
******************************************************************************
* PLEASE NOTE: most display problems are due to incorrect TERM! Before       *
* reporting problems make SURE that TERM settings are correct inside and     *
* outside tmux.                                                              *
*                                                                            *
* Inside tmux TERM must be "screen" or similar (such as "screen-256color").  *
* Don't bother reporting problems where it isn't!                            *
*                                                                            *
* Outside, it must match your terminal: particularly, use "rxvt" for rxvt    *
* and derivatives.                                                           *
******************************************************************************
```

**Comment by abhiravk** [comment]
Hi,

My TERM variable is set to 'xterm-16color' in normal terminal as well as well inside TMUX,

→ echo $TERM
xterm-16color

→ grep default-terminal ~/.tmux.conf
set -g default-terminal "xterm-16color"

is it not supported?

**Comment by mikesart** [comment]
> Is it not supported?

Tmux doesn't support it. Read their faq (link and excerpt in above post).

**Comment by abhiravk** [comment]
Setting TERM to screen-16color does solve the issue.
Thanks.
