### ISSUE TITLE
Source window randomly shows "source and assembly mixed" or "assembly" only

### ISSUE THREAD

**Issue by honggyukim** [cgdb/cgdb#117]
When running cgdb with `:set disasm` mode, it randomly shows sometimes "source and assembly mixed" or "assembly" only. I don't know the exact reason for these behaviors.

**Comment by honggyukim** [comment]
The example program is as follows:
```
$ cat hello.c 
#include <stdio.h>

int main()
{
  printf("Hello World!\n");
  fflush(stdout);
  return 0;
}
```
Then compile it with `-g`
```
$ gcc -pg hello.c
```
Run it with cgdb and set a breakpoint at "main"
```
$ cgdb a.out -ex="b main"
```
Then put "run" and put "step" commands. And it shows
```
 1| Dump of assembler code for function main:
 2| hello.c:
 3| 4       {
 4|    0x00000000004005bd <+0>:     push   %rbp
 5|    0x00000000004005be <+1>:     mov    %rsp,%rbp
 6|
 7| 5         printf("Hello World!
 8|    0x00000000004005c1 <+4>:     mov    $0x400674,%edi
 9|    0x00000000004005c6 <+9>:     callq  0x400490 <puts@plt>
10|
11| 6         fflush(stdout);
12+--> 0x00000000004005cb <+14>:    mov    0x200a7e(%rip),%rax        # 0x601050 <stdout@@GLIBC_2.2.5>
13|    0x00000000004005d2 <+21>:    mov    %rax,%rdi
14|    0x00000000004005d5 <+24>:    callq  0x4004c0 <fflush@plt>
15|
16| 7         return 0;
17|    0x00000000004005da <+29>:    mov    $0x0,%eax
18|
19| 8       }
20|    0x00000000004005df <+34>:    pop    %rbp
21|    0x00000000004005e0 <+35>:    retq   
22| End of assembler dump.
```
But strangely, it sometimes shows the below output in source window:
```
 1| Dump of assembler code for function main:
 2|    0x00000000004005bd <+0>:     push   %rbp
 3|    0x00000000004005be <+1>:     mov    %rsp,%rbp
 4|    0x00000000004005c1 <+4>:     mov    $0x400674,%edi
 5|    0x00000000004005c6 <+9>:     callq  0x400490 <puts@plt>
 6+--> 0x00000000004005cb <+14>:    mov    0x200a7e(%rip),%rax        # 0x601050 <stdout@@GLIBC_2.2.5>
 7|    0x00000000004005d2 <+21>:    mov    %rax,%rdi
 8|    0x00000000004005d5 <+24>:    callq  0x4004c0 <fflush@plt>
 9|    0x00000000004005da <+29>:    mov    $0x0,%eax
10|    0x00000000004005df <+34>:    pop    %rbp
11|    0x00000000004005e0 <+35>:    retq
12| End of assembler dump.
```

**Comment by mikesart** [comment]
If I just compile with "-g", I don't get any symbols at all even with straight gdb. If I compile with "-g2", I get symbols but I can't reproduce this bug in cgdb.

Also, there appears to be a bug in line 5 where it says "printf("Hello World!", not "printf("Hello World!\n");

```
$ gcc -pg hello.c

$ gdb --quiet a.out
Reading symbols from a.out...(no debugging symbols found)...done.

(gdb 7.12.0.20161007-git: <no frame>) disassemble /s main
Dump of assembler code for function main:
   0x0000000000000890 <+0>:	push   rbp
   0x0000000000000891 <+1>:	mov    rbp,rsp
   0x0000000000000894:	call   QWORD PTR [rip+0x20073e]        # 0x200fd8
   0x000000000000089a:	lea    rdi,[rip+0xdb]        # 0x97c
   0x00000000000008a1:	call   0x6c0 <puts@plt>
   0x00000000000008a6:	mov    rax,QWORD PTR [rip+0x20079b]        # 0x201048 <stdout@@GLIBC_2.2.5>
   0x00000000000008ad:	mov    rdi,rax
   0x00000000000008b0:	call   0x6e0 <fflush@plt>
   0x00000000000008b5:	mov    eax,0x0
   0x00000000000008ba:	pop    rbp
   0x00000000000008bb:	ret    
End of assembler dump.
```
Compiling with -g2 works though.
```
$ gcc -p -g2 hello.c

$ gdb --quiet a.out
Reading symbols from a.out...done.

(gdb 7.12.0.20161007-git: <no frame>) disassemble /s main
Dump of assembler code for function main:
hello.c:
4	{
   0x0000000000000890 <+0>:	push   rbp
   0x0000000000000891 <+1>:	mov    rbp,rsp
   0x0000000000000894:	call   QWORD PTR [rip+0x20073e]        # 0x200fd8

5	  printf("Hello World!\n");
   0x000000000000089a:	lea    rdi,[rip+0xdb]        # 0x97c
   0x00000000000008a1:	call   0x6c0 <puts@plt>

6	  fflush(stdout);
   0x00000000000008a6:	mov    rax,QWORD PTR [rip+0x20079b]        # 0x201048 > <stdout@@GLIBC_2.2.5>
   0x00000000000008ad:	mov    rdi,rax
   0x00000000000008b0:	call   0x6e0 <fflush@plt>

7	  return 0;
   0x00000000000008b5:	mov    eax,0x0

8	}
   0x00000000000008ba:	pop    rbp
   0x00000000000008bb:	ret    
End of assembler dump.
```

Here are the versions I'm running with.

```
$ gcc --version
gcc (Debian 6.3.0-5) 6.3.0 20170124
```
```
$ gdb --version
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
```

**Comment by honggyukim** [comment]
Hi @mikesart,

It seems that you compiled with `-pg` option instead of `-g` option in the first log above.

My version info is as follows:
```
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```
```
$ gdb --version
GNU gdb (GDB) 7.12
```
I also tested it with gdb v.7.11.1 but it doesn't make difference.
Thanks!

**Comment by brasko** [comment]
When I run this example I seem to always get mixed source and assembly.

I also reproduce the syntax highlighting issue. Also, the assembly highlighting is
terrible. The entire file shows as red for me. That would certainly be an area for
improvement. Wonder what's causing the random behavior here.

@honggyukim - How hard is it for you to reproduce it both ways? We could
perhaps add some better logging into cgdb to help us diagnose the point
of failure.

**Comment by honggyukim** [comment]
> I also reproduce the syntax highlighting issue. Also, the assembly highlighting is
terrible. The entire file shows as red for me. That would certainly be an area for
improvement. Wonder what's causing the random behavior here.

Do you mean the syntax highlighting issue in #119 ?

> @honggyukim - How hard is it for you to reproduce it both ways? We could
perhaps add some better logging into cgdb to help us diagnose the point
of failure.

I don't know the exact execution sequence to reproduce it but sometimes it appears.
I also tested it in Ubuntu 16.04 LTS but it doesn't have any problem. I will tell you if I find the exact execution sequence to reproduce it later on.

Thanks for your help!

**Comment by brasko** [comment]
@honggyukim, in the current master, can you still reproduce this problem?

I've made some significant improvements to cgdb that I could see potentially solving this.
Since I can't reproduce the issue, I'm not sure.

**Comment by honggyukim** [comment]
@brasko I've tested it for a while but didn't find the problem as of now. It's okay to close the issue but I will reopen it if I find the same problem later. Thanks for your effort!

**Comment by brasko** [comment]
Thanks!
