### ISSUE TITLE
The arrow is not properly updated as executed a single instruction

### ISSUE THREAD

**Issue by honggyukim** [cgdb/cgdb#118]
As mentioned in #44, The arrow is not properly updated when I keep running "si" commands.
It can be reproduced with the same example with #117. After hitting a breakpoint, then just keep running "si" commands but it doesn't update the arrow.

**Comment by honggyukim** [comment]
I think that until 73f75ef is good, but have some problems on the later changes. I was not able to spot the right commit because some of the later versions are just crashed.

**Comment by brasko** [comment]
@honggyukim Could you please retest this in master? I've made many fixes and think it's possible this has been fixed.

**Comment by brasko** [comment]
Thanks!
