### ISSUE TITLE
make failed in CentOS 6.8 2.6.32-642.el6.x86_64 gcc: 4.4.7 20120312

### ISSUE THREAD

**Issue by wxx422** [cgdb/cgdb#120]
I do as follow:
$ git clone git://github.com/cgdb/cgdb.git
$ cd cgdb
$ ./autogen.sh
yum install ncurses-devel
yum install texinfo
yum install help2man
yum install readline-devel
yum install flex
$ ./configure --prefix=/usr/local
$ make
report error as:
gdbwire.c:1577: error: redefinition of typedef 'yyscan_t'
gdbwire.c:3355: error: redefinition of typedef 'yyscan_t'
gdbwire.c:3409: error: redefinition of typedef 'YY_BUFFER_STATE'

**Comment by brasko** [comment]
Fixed!
