### ISSUE TITLE
Cursor offset gets lost when typing UTF-8 characters in the gdb window

### ISSUE THREAD

**Issue by ibuclaw** [cgdb/cgdb#121]
Follow-up from #9, I'll try to represent this visually where `|` is the cursor position on the screen.

Typing in `p 'пример'`
```
(gdb) |
(gdb) p|
(gdb) p |
(gdb) p '|
(gdb) p 'п |
(gdb) p 'пр   |
(gdb) p 'при    |
(gdb) p 'прим     |
(gdb) p 'приме      |
(gdb) p 'пример       |
(gdb) p 'пример'       |
```
Pressing backspace.
```
(gdb) p 'пример'       |
(gdb) p 'пример       |
(gdb) p 'пример      |
(gdb) p 'приме      |
(gdb) p 'приме     |
(gdb) p 'прим     |
(gdb) p 'прим    |
(gdb) p 'при    |
(gdb) p 'при   |
(gdb) p 'пр   |
(gdb) p 'пр  |
(gdb) p 'п  |
```
Typing in `qwerty`
```
(gdb) p 'п  |
(gdb) p 'п w  |
(gdb) p 'п we  |
(gdb) p 'п wer  |
(gdb) p 'п wert  |
(gdb) p 'п werty  |
```
Moving the cursor from right to left.
```
(gdb) p 'п werty  |
(gdb) p 'п werty |
(gdb) p 'п werty|
(gdb) p 'п wert|y
(gdb) p 'п wer|ty
(gdb) p 'п w|erty
```
Then from left to right
```
(gdb) p 'п w|erty
(gdb) q| 'п werty
(gdb) qw|'п werty
(gdb) qwe|п werty
(gdb) qwer|M-? werty
(gdb) qwert|y werty
(gdb) qwerty|qwerty
```
Visually, it looks like the end result is `(gdb) qwertyqwerty` but actually, it's just the one present.

**Comment by brasko** [comment]
I've finally made some progress on integrating cgdb with libvterm.
@ibuclaw  Could you please build cgdb from the libvterm branch and let me know if it resolves all the issues found above?

**Comment by ibuclaw** [comment]
Thanks @brasko. With the following C program, using Cyrillic is fine, thought there's still a little oddity in printing and handling CJK characters - so UTF16 is seems fine, but UTF32 still causes some confusion.

```
#include <stdio.h>
int main()
{
    const char *пример = "aaa";
    const char *世界 = "bbb";
    printf("%s%s\n", пример, 世界);
    return 0;
}
```
There's a tilde that appears after the character that throws off the cursor position.
![image](https://user-images.githubusercontent.com/397929/130198072-df2e7a17-11c5-49f7-ac5d-97c9dc9bb352.png)

**Comment by auouymous** [comment]
This is the same issue I described in #257 with the tilde after wide characters.

**Comment by brasko** [comment]
@ibuclaw  I believe I've just pushed a fix for this, do you mind testing for me? The fix is in the libvterm branch.

**Comment by ibuclaw** [comment]
@brasko looks good from here, thanks!

**Comment by brasko** [comment]
I've integrated the libvterm branch into master. This should have fixed this issue. Please let me know otherwise. Thanks!
