### ISSUE TITLE
cgdb 0.7.0 does not cross compile anymore...

### ISSUE THREAD

**Issue by ElTopo** [cgdb/cgdb#125]
due to AC_TRY_RUN in configure for "checking Checking attribute printf support".

Apparently, [action-if-cross-compiling] is missing from AC_TRY_RUN.

I also recommend that you use an ac_cv_env. My cross compiler does support attribute printf.

**Comment by brasko** [comment]
The attribute stuff is really just for safety. We could perhaps have a configure switch to disable it.

Would that work?

**Comment by brasko** [comment]
OK, should cross compile again. Let me know otherwise.
