### ISSUE TITLE
Syntax highlighting not working on mixed source + asm

### ISSUE THREAD

**Issue by ibuclaw** [cgdb/cgdb#128]
Simple enough test:
```
#include <stdio.h>

int main()
{
    printf("Hello World!\n");
    return 0;
}
```

When turning on disassembly, the result is that `\n");` becomes missing.
```
 5           printf("Hello World!
 8├──> 0x000000000040057e <+4>:     mov    $0x400614,%edi
 9│    0x0000000000400583 <+9>:     callq  0x400450 <puts@plt>
```

Trying to find the culprit, so far I've only managed to determine:
```
-- gdbwire_mi_parser_get_next_line: ~"5\t    printf(\"Hello World!\\n\");\n"
-- gdbwire_mi_parser_parse_line: ~"5\t    printf(\"Hello World!\\n\");\n"
-- gdbwire_stream_record_callback: 5	    printf("Hello World!
");
```
Somewhere between parser_parse_line and stream_record_callback, the escaped newline in `"Hello World\n"` becomes unescaped.

**Comment by brasko** [comment]
Thanks, it's probably in gdbwire_mi_parser_parse_line. Maybe it's getting called when it shouldn't be.
I'll try to track this down later.

**Comment by ibuclaw** [comment]
I just so happened to be having another look at it when you chimed in.  Looks like `gdbwire_mi_unescape_cstring` is the culprit.

This naive change makes the problem go away.
```
--- a/lib/tgdb/gdbwire.c
+++ b/lib/tgdb/gdbwire.c
@@ -5488,6 +5488,8 @@ static char *gdbwire_mi_unescape_cstring(char *str)
                 case '"':
                     break;
                 case '\\':
+                    result[r++] = '\\';
+                    ++s;
                     break;
                 default:
                     result[r++] = str[s];
```

**Comment by brasko** [comment]
Wow! So sorry. That's the function name I meant to write. I must have had a bad paste.

I'll review your patch later today. Thanks!

**Comment by brasko** [comment]
Thanks, hopefully this works out.

**Comment by ibuclaw** [comment]
I had a cursory test, and things looked good.  I'll let you know if I spot anything on more complex code, should be fixed though by the looks. ;-)
