### ISSUE TITLE
cgdb stucks on fgets

### ISSUE THREAD

**Issue by zhenglu0** [cgdb/cgdb#130]
I ran into issue while debuging other program and confirm the issue with the simple example below:

```c
#include <stdio.h>
#include <string.h>

#define BUFFERSIZE 10

int main (int argc, char *argv[])
{
    char buffer[BUFFERSIZE];
    printf("Enter a message: \n");
    while(fgets(buffer, BUFFERSIZE , stdin) != NULL)
    {
        printf("MESSAGE: %s\n", buffer);
    }
    return 0;
}

```
cgdb stucked on the line fgets and does not make any progress there.

**Comment by RogerFederer03** [comment]
This limitation is described in the document

**Comment by brasko** [comment]
This should be fixed in the new-ui branch. Please let me know. Thanks.

**Comment by brasko** [comment]
Fixed in master
