### ISSUE TITLE
Toggle key to and from CGDB/GDB modes

### ISSUE THREAD

**Issue by spearman** [cgdb/cgdb#134]
Ideally it would be something like SHIFT-TAB.

The easiest way seems to be just use cgdb_mode_key: https://github.com/cgdb/cgdb/pull/133

**Comment by brasko** [comment]
Could you use key mappings to accomplish your goal here?
In your ~/.cgdb/cgdbrc put
map <Left> i
imap <Left> <ESC><CR>

Unfortunately, you can't map S-Tab right now. However, if you like this solution, I can add
that support for you.

**Comment by spearman** [comment]
`map <Esc> i` that works for me.

Is there a way to add mappings to scroll mode? The behavior I keep expecting is to hit Esc to return to gdb mode. It would also be nice if PageDown when at the bottom of the scroll window would return to gdb mode as well:
```
*not at bottom*
<PageDown>
*now at bottom*
<PageDown>
*back in gdb mode*
```

**Comment by brasko** [comment]
https://cgdb.github.io/docs/cgdb.html#Using-Maps

map works in cgdb mode
imap works in gdb mode

Let me know if you require further help
