### ISSUE TITLE
Show appropriate logos when color disabled

### ISSUE THREAD

**Issue by 10110111** [cgdb/cgdb#139]
See the [screenshot](https://user-images.githubusercontent.com/6376882/28742365-a59c4424-743e-11e7-83f5-f0b1c99d24d0.png).

If we give the "empty" logo number 1, then broken ones are 2,3,7. This doesn't reproduce with `set nocolor` and `TERM=xterm-256color`. In fact, `set nocolor` seems to do nothing in this case — I get colorful logos on `:logo`.

**Comment by brasko** [comment]
Should be fixed, let me know otherwise!

**Comment by 10110111** [comment]
Confirming fixed.
