### ISSUE TITLE
Readline error lacks details

### ISSUE THREAD

**Issue by leto** [cgdb/cgdb#14]
```
configure: error: CGDB requires GNU readline 5.1 or greater to link.
  If you used --with-readline instead of using the system readline library,
  make sure to set the correct readline library on the linker search path
  via LD_LIBRARY_PATH or some other facility.
```

It would be nice if this error included the version of readline detected (I think I have 6.2.4 installed), as well as some useful URLs or commands to install it.

**Comment by wujinggrt** [comment]
This problem occurs when I execute ./autogen.sh on Ubuntu 19.04, sovling it by:

 $ sudo apt-get install libreadline-dev.

Then,  do as http://cgdb.github.io suggests.

**Comment by owenstake** [comment]
In centos, do this
```bash
yum install readline-devel
```
