### ISSUE TITLE
print /x fails to complete struct

### ISSUE THREAD

**Issue by jreybert** [cgdb/cgdb#143]
Giving the following snip of code:
```
 struct foo {
         int a;
 };
 struct foo test;
 int main() {
         return 0;
 }
```

Compiling as `cc -g3    cgdb_comp_fail.c   -o cgdb_comp_fail`

If I try to complete the `test` variable on a print line, like:
```
(gdb) print test.<TAB>
```
It ends with `test.a`

But if I try to complete with:
```
print /x test.<TAB>
Display all 278 possibilities? (y or n)
```

It ends like it almost did not recognize `test.` string.

For the record, trying to complete an empty string gives the following output:
```
(gdb) print
Display all 280 possibilities? (y or n)
```

**Comment by brasko** [comment]
Unfortunately, this is due to the way that cgdb does tab completion with gdb at arms length.

There are a lot of issues where this isn't perfect. I'm not even exactly sure how to fix these issues
at the moment.

**Comment by jreybert** [comment]
I would to take a look into it. Could you give some pointers, where should I start digging?

**Comment by jreybert** [comment]
Actually, it is problem in gdb itself:
https://sourceware.org/bugzilla/show_bug.cgi?id=16256

If you don't mind, do not close the ticket. I would to dig into other gdb frontend to see if they use workaround for this issue.

**Comment by brasko** [comment]
So cgdb (in master) now uses gdb's readline, so if there are any print issues, it would be with gdb and not cgdb.
Let me know if you have any further updates.
