### ISSUE TITLE
Add support for setting history file path and duplicate removal

### ISSUE THREAD

**Issue by segevfiner** [cgdb/cgdb#144]
It would be nice if it was possible to set the path to the history file. This will be useful if you are already using the plain gdb history support, so that you can use the same file for both cgdb and gdb, without setting gdb to use the cgdb specific history file path.

Another nice improvement for history support is duplicate removal. This means removing duplicate history lines so that you won't find yourself pressing up and seeing the same input line. (I think this isn't builtin to readline/history library). It's important to allow to control how far the deduplication look back looks or at least have it always at 1, like bash does when enabled. (See `HISTCONTROL` here: [Bash Variables](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html))

Essentially this issue is about bringing the history support to feature parity with gdb's builtin history support (Note that gdb also allows setting the history file size).

See [GDB Command History](https://sourceware.org/gdb/onlinedocs/gdb/Command-History.html) for the gdb builtin settings for history.

**Comment by brasko** [comment]
OK. These ideas seem good in general.
In lib/rline/rline.h I have the function, rline_read_history which reads in the history file.
It's called once in cgdb.c:init_readline, and reads the history file in cgdb's configuration directory.

I wonder if users would want to sometimes share the gdb history, and sometimes have cgdb
have it's own history. That would require an option. Thoughts?

**Comment by segevfiner** [comment]
> I wonder if users would want to sometimes share the gdb history, and sometimes have cgdb
have it's own history. That would require an option. Thoughts?

You can see which settings gdb supports in the link [GDB Command History](https://sourceware.org/gdb/onlinedocs/gdb/Command-History.html). Essentially it has:
1. A setting for the file name. Which would allow to select if to share or not share the history.
2. A setting for enabling/disabling history.
3. A setting for the history file size.
4. A setting for duplicate removal.

It's nice to aim for feature parity with that, since that's what plain gdb supports. I think it's implemented here: [binutils-gdb.git/gdb/top.c](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=gdb/top.c;h=ed109344b2838eff16805698b0cf91d2aa37c517;hb=HEAD).

P.S. I do hope that gdb's own history code is truly disabled when working under cgdb.

**Comment by brasko** [comment]
CGDB now uses gdb's readline instead of it's own. That means all of the use cases you were hoping to see work in cgdb probably do now. I'm closing this as fixed.
