### ISSUE TITLE
`:set dis` enables showing assembly code but does not disable it

### ISSUE THREAD

**Issue by jmuchemb** [cgdb/cgdb#151]
The help says that `:set dis` toggles the view of assembly code, and that would be great, but that's not what happens. Executing `:set dis` a first time does show a mixed of assembly and source code but executing it again does nothing. Even if I reopen the source file, any command (e.g. `step`) switches again the dis view.

**Comment by annagrram** [comment]
In Vim, `:set` just sets the setting. In order to unset it, you use `:set no<setting>`.
So, in this case `:set nodis` will disable the dis setting and return you to code view.

**Comment by jmuchemb** [comment]
I confirm that `:set nodis` does return to the source-only view. I missed that in the help, at the beginning of the `4 CGDB configuration commands`.

Unfortunately, with this way of enabling/disabling things, there's no way to toggle with a single key binding, and that's what I actually wanted to do. I'll open a new issue for that.

**Comment by annagrram** [comment]
Please try the fix in https://github.com/annagrram/cgdb branch: inverse_variable.
The syntax is `:set inv<variable>`.
For example, `:set invdis`.
If it works as intended, I'll open a pull request.

**Comment by jmuchemb** [comment]
Thank you. It works.

**Comment by annagrram** [comment]
Opened a PR #156
