### ISSUE TITLE
Optional binding of <PageUp> in GDB mode

### ISSUE THREAD

**Issue by jmuchemb** [cgdb/cgdb#153]
Currently, it automatically switches to scroll mode, but as a heavy user of `history-search-backward` (readline), this is something I'd like to disable. There's still `<Esc>+s` if I want to scroll.

Actually, I wonder why the default bindings are implemented in C. Why not split `gdb_input` and `cgdb_input` functions into reusable actions (many exist already like `next`) and have a default configuration that is processed before anything else.

Then `iunmap <PageUp>` would do what I'd like.

(BTW, I tried `imap <PageUp> <PageUp>` and once I pressed `<PageUp>`, cgdb entered an infinite loop.)

**Comment by annagrram** [comment]
What about Ctrl+R?

About the side-note - if you map a key to itself it will surely go into an infinite loop.
In Vim you can avoid that with `inoremap` but I don't think cgdb supports that at the moment.

**Comment by jmuchemb** [comment]
I know Ctrl+R but it's more a search feature than a shortcut one. I find it less efficient for most cases.

> if you map a key to itself it will surely go into an infinite loop.

Even if remapping is useful, loops could be detected.

**Comment by annagrram** [comment]
As the interface of cgdb is stated to be modeled after Vim, I'll keep using it as a baseline for my answers.
You can't unmap basic keys in Vim, but you can certainly override them with new mappings.
How about doing `:imap <PageUp> <C-R>`?

> Even if remapping is useful, loops could be detected.

That's not entirely true.
Detecting `:imap <PageUp> <PageUp>` is easy.
Detecting `:imap <PageUp> <PageDown>` and `:imap <PageDown> <PageUp>` is a bit more complicated.
In the general case it is proven to be unsolvable (The Halting Problem).
So, one does not want to get into that. Vim doesn't get into that either.

**Comment by brasko** [comment]
These are good points. As I read this I potentially see a few problems.

What specific first action should we consider taking?

**Comment by brasko** [comment]
Is anyone still interested in this case? If so, please let me know and we can discuss. Otherwise I'll close it in a week.

**Comment by iandinwoodie** [comment]
@brasko sounds like it can be closed.

**Comment by brasko** [comment]
agreed
