### ISSUE TITLE
how to set gdb outputs in colors? by .gdbinit?

### ISSUE THREAD

**Issue by yuanshuoastro** [cgdb/cgdb#155]
Dear CGDB developers,
I am trying to make the "gdb" output in colors. 
In .gdbinit, I can do something like 

`set prompt \001\033[1;33m\002(gdb) \001\033[0m\002 `

This will make the prompt of (gdb) in color in gdb/cgdb. 

I am not sure how to make some other gdb output in colors as well, e.g. the "bt", "info b" etc.

Is there any way to warp/rewrite some function in .gdbinit then made the output in colors?

Thanks!

**Comment by brasko** [comment]
The goal of CGDB is to support colors the same way GDB would. The prompt is actually
the only configuration that I use to change colors as well. I would look to the gdb mailing list
or documentation for more help on this. If you find a case that GDB supports and CGDB doesn't,
let us know for sure!

Thanks for using CGDB.
