### ISSUE TITLE
Logging output uses machine interface?

### ISSUE THREAD

**Issue by shihyu** [cgdb/cgdb#158]
Hi,

when I use "set logging on" in cgdb, the output to the log file is in
Machine Interface mode. 

it's the same problem as  stackoverflow:
http://stackoverflow.com/questions/3862210/gdb-log-file-format

Thanks.

**Comment by xiangp126** [comment]
I meet the same problem, seems not fixed yet for v0.7.0

**Comment by brasko** [comment]
At some point, I hope to move away from communicating with GDB using annotations.
I think this will help resolve the problem.

**Comment by brasko** [comment]
This appears to be fixed in the new-ui branch. Please let me know if you agree. Thanks.

**Comment by brasko** [comment]
Fixed in master
