### ISSUE TITLE
cgdb not showing source code

### ISSUE THREAD

**Issue by kaisoz** [cgdb/cgdb#16]
I'm trying cgdb with the following configuration:
- Ubuntu 12.10 64bit
- cgdb 0.6.7 compiled from source
- gdb 7.5-ubuntu

And everytime I try cgdb, no matter if remote or local debugging, it does not show source code. However, gdbtui and gdb "list" comand are able to show the source code perfectly

Is there any kind of issue with this version of gdb?

Thank you

**Comment by mmodenesi** [comment]
Same issue.

I run

`cgdb <prog_name>`

It's a one-file program, just messing arrond to explore cgdb.

I am able to debug but on source window I see initial msg (ascii art, a curses debugger version 0.6.7, type...). If I jump to source window and press 'o', I see only  <prog_name>.c (whith full path). I select it and it says `No such file: <full_path_to_prog_name>`.

Of course, file exists.

**Comment by mmodenesi** [comment]
Cause of the problem and workarround:

https://groups.google.com/forum/#!topic/cgdb-users/fXtEh8KZ19s

**Comment by mikesart** [comment]
Closing really old issues. Please open a new bug if this problem still exists. Hopefully not since we've moved from annotations to gdb/mi... Thanks.
