### ISSUE TITLE
GDB command-line options not working

### ISSUE THREAD

**Issue by darsor** [cgdb/cgdb#160]
`cgdb --help` says that GDB options can be passed in the following way:

```
CGDB Usage:
   cgdb [cgdb options] [--] [gdb options]
```

I am trying to use GDB's `-tty` option to set the tty for the program's input/output. I've tried several methods:
```
cgdb ./a.out -- -tty=/dev/pts/3             # does not set the tty, with or without the double dash
cgdb ./a.out -- -ex="tty /dev/pts/3"     # also doesn't work
cgdb ./a.out -- -ex="b main"                 # works as expected (?)
```

Running `tty /dev/pts/3` inside CGDB works. So why doesn't the `-tty` option work, and why does the `-ex` option work when setting breakpoints but not when setting the tty?

**Comment by brasko** [comment]
OK sorry.

You found one of the few options that dooesn't naturally work.
Why? because cgdb uses the tty option itself to separate the gdb output
from the debugged
programs output.

A user recently ran into this problem and modified cgdb's source to work
around the problem.

I guess I should make this optional.

**Comment by darsor** [comment]
What do you mean by that? It doesn't seem like cgdb separates gdb output from the debugged program's output.

What is the proper way to change the debugged program's tty in cgdb using a script?

**Comment by brasko** [comment]
Basically, as far as I know, the --tty flag is the only one not supported by CGDB, as CGDB issues
the tty gdb command, which would override the --tty flag anyways.

I'm going to add support directly into cgdb to optionally not use the tty flag. That should resolve your issue.

**Comment by brasko** [comment]
In the new-ui branch this issue should be resolved. Please give it a try and let me know. Thanks.

**Comment by brasko** [comment]
CGDB no longer requires the tty option, so you should be able to set it as you wish. Fixed in master.
