### ISSUE TITLE
cgdb stuck after search keywords by press 'TAB' in source window

### ISSUE THREAD

**Issue by tanghammer** [cgdb/cgdb#161]
environment:
  CGDB 0.7.0
  GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
  CentOS 7

step:
1. cgdb ./test.
2. in cgdb mode, press 'o' ,open another source file .
3.press '/' then press 'TAB'.
4.cgdb stuck.

i use gdb trace cgdb

(gdb) bt
---------------------------------------------------------------------------------------------------------------
#0  0x00007f463a66c3cd in re_search_internal () from /lib64/libc.so.6
#1  0x00007f463a672fb5 in regexec@@GLIBC_2.3.4 () from /lib64/libc.so.6
#2  0x000000000040a5e4 in hl_regex_search (info=info@entry=0x1ce12b8, line=0x1cf8b4a "    if ( SQLITE_OK != sqlite3_get_table(mdb->db, tmp, &azResult, &nRow, &nColumn, NULL) )", 
    regex=regex@entry=0x1d05950 "<C-i>", icase=icase@entry=0, start=start@entry=0x7ffc0166c3c8, end=end@entry=0x7ffc0166c3cc) at highlight.cpp:95
#3  0x0000000000411cb6 in source_search_regex (sview=sview@entry=0x1ce10e0, regex=0x1d05950 "<C-i>", opt=opt@entry=1, direction=direction@entry=1, icase=icase@entry=0) at sources.cpp:1326
#4  0x000000000040d001 in status_bar_regex_input (key=<optimized out>, sview=0x1ce10e0) at interface.cpp:1070
#5  status_bar_input (key=<optimized out>, sview=0x1ce10e0) at interface.cpp:1139
#6  internal_if_input (key=<optimized out>, last_key=last_key@entry=0x7ffc0166d44c) at interface.cpp:1598
#7  0x000000000040ded2 in if_input (key=<optimized out>) at interface.cpp:1608
#8  0x0000000000405e2f in user_input () at cgdb.cpp:924
#9  user_input_loop () at cgdb.cpp:975
#10 0x0000000000404e0a in main_loop () at cgdb.cpp:1429
#11 main (argc=<optimized out>, argv=<optimized out>) at cgdb.cpp:1809
---------------------------------------------------------------------------------------------------------------
Thank you for looking into this issue!

**Comment by brasko** [comment]
Reproduced, thanks, will look into this.

**Comment by brasko** [comment]
Fixed, let me know if you have any further problems!
