### ISSUE TITLE
Compilation fails, missing -std=c++11

### ISSUE THREAD

**Issue by kraiskil** [cgdb/cgdb#163]
Trying to compile cgdb from git ( 64409f1,  Nov 22, 2017) fails on Ubuntu 16.04 with its default gcc
(gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5))
`./autogen.sh && ./configure && make`
Running 
` CXXFLAGS=-std=c++11 ./configure && make` makes it work.

Perhaps this flag could be added as a default for g++?

**Comment by brasko** [comment]
I'm not sure what to do here. Some older versions of gcc might require the C++11, but newer versions do not. I'm not sure what to do here. Would documenting that C++11 is required good enough?

**Comment by brasko** [comment]
I've documented that C++11 is required in the README.md, and showed how to set the flags.
Hopefully this resolves this issue.

**Comment by kraiskil** [comment]
Sorry, I missed the first reply. 
GCC 6 bumped its default C++ standard from gnu++98 to gnu++14, hence the issue. Therefore, adding a '-std=c++11' for all gcc:s should not break the compilation for newer gcc:s.
