### ISSUE TITLE
[QUESTION] how to switch to intel disassembly syntax ?

### ISSUE THREAD

**Issue by kamou** [cgdb/cgdb#164]
Hello,
 I see you have added the `:set disasm` option wich is great news :)
But I personally am more comfortable reading intel syntax then default AT&T syntax.
Is there a way to change that ?

**Comment by amosbird** [comment]
Just put `set disassembly-flavor intel` in your gdb's init file.

**Comment by kamou** [comment]
oh ! Didn't think this was related, stupid me !
thanks !
