### ISSUE TITLE
There was an error installing to rustlexer.cpp,  v0.7.0 release

### ISSUE THREAD

**Issue by wettper** [cgdb/cgdb#165]
Making all in tokenizer
make[3]: Entering directory `/src/cgdb-0.7.0/lib/tokenizer'
g++ -DHAVE_CONFIG_H -I. -I../..    -I../../lib/adt -I../../lib/util -g -O2 -MT adalexer.o -MD -MP -MF .deps/adalexer.Tpo -c -o adalexer.o adalexer.cpp
mv -f .deps/adalexer.Tpo .deps/adalexer.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I../../lib/adt -I../../lib/util -g -O2 -MT clexer.o -MD -MP -MF .deps/clexer.Tpo -c -o clexer.o clexer.cpp
mv -f .deps/clexer.Tpo .deps/clexer.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I../../lib/adt -I../../lib/util -g -O2 -MT asmlexer.o -MD -MP -MF .deps/asmlexer.Tpo -c -o asmlexer.o asmlexer.cpp
mv -f .deps/asmlexer.Tpo .deps/asmlexer.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I../../lib/adt -I../../lib/util -g -O2 -MT dlexer.o -MD -MP -MF .deps/dlexer.Tpo -c -o dlexer.o dlexer.cpp
mv -f .deps/dlexer.Tpo .deps/dlexer.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I../../lib/adt -I../../lib/util -g -O2 -MT golexer.o -MD -MP -MF .deps/golexer.Tpo -c -o golexer.o golexer.cpp
mv -f .deps/golexer.Tpo .deps/golexer.Po
g++ -DHAVE_CONFIG_H -I. -I../..    -I../../lib/adt -I../../lib/util -g -O2 -MT cgdbhelplexer.o -MD -MP -MF .deps/cgdbhelplexer.Tpo -c -o cgdbhelplexer.o cgdbhelplexer.cpp
mv -f .deps/cgdbhelplexer.Tpo .deps/cgdbhelplexer.Po
/bin/sh ../../config/ylwrap rustlexer.lpp lex.yy.c rustlexer.cpp -- flex
make[3]: *** [rustlexer.cpp] Error 1
make[3]: Leaving directory `/src/cgdb-0.7.0/lib/tokenizer'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/src/cgdb-0.7.0/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/src/cgdb-0.7.0'
make: *** [all] Error 2

**Comment by brasko** [comment]
Yes, this was fixed master, no new release yet. In NEWS see,


  * The rust syntax highlighter is now case sensitive instead of case
    insensitive.

  * Fix issue #137. rustlexer.lpp fails to compile with some versions
    of GNU autotools.
