### ISSUE TITLE
form-feed character (^L) clears the whole screen

### ISSUE THREAD

**Issue by ghost** [cgdb/cgdb#166]
when using commandline, I tend to use CTRL+L to clear the logs of what I did, so that I could focus on output of the next command.
Doing so in cgdb, clears the whole terminal, and if it is possible to get back to a more or less working state, it is still corrupted in some way.

What I would expect is either:

* having a "^L" on the prompt, or nothing at all if it is not supported;
* or having only the window which was focused cleaned up;
* or considering it have no sens outside of the gdb prompt, so ignore everywhere but there.

**Comment by brasko** [comment]
Are you using the latest version of CGDB? This behavior has changed.

Could you try the last release, cgdb-0.7.0 (03/21/2017), and see if it works as expected?
