### ISSUE TITLE
Display error in the code window

### ISSUE THREAD

**Issue by Ytinifni-zc** [cgdb/cgdb#167]
Something wrong with displaying the edge of code window and the arrow.
Version of my compilers are:
- gcc: 7.2.0
- gdb: GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
- python: anaconda3
<img width="892" alt="cgdb-bug" src="https://user-images.githubusercontent.com/2703676/38068827-ce186eb6-3345-11e8-8713-ab8041bcb195.png">

**Comment by Ytinifni-zc** [comment]
@brasko I'm afraid it's hard to reproduce. I guess there is some conflict between cgdb's UI and my terminal's display. But I didn't find cgdb's configurations about cgdb's fonts or stuff.
Do you have any idea about this?

**Comment by brasko** [comment]
I've had similar issues in different setups, and after careful reporting, ncurses dev told me it's probably a terminal bug. With that said, if it's reproducible, I'll be happy to take a look, otherwise. Until then, I'll close the case, but I appreciate the report.
