### ISSUE TITLE
cgdb stucked

### ISSUE THREAD

**Issue by tanghammer** [cgdb/cgdb#183]
when i  use 'commands' command to set  breakpoint command lists, press tab ,cgdb will stucked.tab is auto complement.

**Comment by idinwoodie** [comment]
@tanghammer are you still experiencing this issue? If you are experiencing the issue, can you provide the following:
1. Your operating system
2. Your cgdb version
3. Your gdb version

**Comment by brasko** [comment]
This is a duplicate of issue #67. Closing this one.
