### ISSUE TITLE
| and arrow (->) characters are shown as ^@

### ISSUE THREAD

**Issue by lonAlpha** [cgdb/cgdb#185]
Hi, 

In my terminal , some characters are not shown correctly. 
$ cgdb --version
CGDB 0.6.8
$ uname -a
Linux myhost 2.6.32-431.11.2.el6.x86_64 #1 SMP Mon Mar 3 13:32:45 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 6.5 (Santiago)

This issue happens in both Konsole version 2.3.3 and GNOME-TERMINAL 2.31.3

![cgdb_issue](https://user-images.githubusercontent.com/5145579/44507576-a91c7d80-a6dd-11e8-962e-f150434c3e4b.png)

**Comment by lonAlpha** [comment]
Just now I find that it is due to incompatible LD_LIBRARY_PATH setting.

**Comment by idinwoodie** [comment]
@lonAlpha can you please provide the incompatible `LD_LIBRARY_PATH` setting so that it is documented?

**Comment by lonAlpha** [comment]
@idinwoodie 
/grid/common/lib is a shared library path and the ncurses is version 5.6. 

ldd output after removing /grid/common/lib from LD_LIBRARY_PATH
```
$ ldd ~/mylocal/bin/cgdb
        linux-vdso.so.1 =>  (0x00007fffb3776000)
        libreadline.so.5 => /home/user/mylocal/lib/libreadline.so.5 (0x000000399fe00000)
        libncurses.so.5 => /lib64/libncurses.so.5 (0x0000003e1c200000)
        libm.so.6 => /lib64/libm.so.6 (0x0000003e05200000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003e05600000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000003e05a00000)
        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x0000003e13600000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003e04e00000)
```

ldd output after adding /grid/common/lib from LD_LIBRARY_PATH
```
$ setenv LD_LIBRARY_PATH $LD_LIBRARY_PATH:/grid/common/lib
$ ldd ~/mylocal/bin/cgdb
        linux-vdso.so.1 =>  (0x00007ffff05ca000)
        libreadline.so.5 => /home/user/mylocal/lib/libreadline.so.5 (0x000000399fe00000)
        libncurses.so.5 => /grid/common/lib/libncurses.so.5 (0x00002b9d82973000)
        libm.so.6 => /lib64/libm.so.6 (0x0000003e05200000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003e05600000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000003e05a00000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003e04e00000)
```

```
 ll /lib64/libncurses.so.5
lrwxrwxrwx. 1 root root 17 Mar 15  2017 /lib64/libncurses.so.5 -> libncurses.so.5.7
 ll /grid/common/lib/libncurses.so.5
lrwxrwxrwx 1 matrix company 50 Jan  6  2014 /grid/common/lib/libncurses.so.5 -> /grid/common/pkgs/ncurses/v5.6/lib/libncurses.so.5
```

**Comment by brasko** [comment]
Closing issue as this is a curses setup issue. Please let me know if I'm incorrect and we'll reopen.
