### ISSUE TITLE
cgdb in Cloud9: Code view does update to currently executed line.

### ISSUE THREAD

**Issue by biocyberman** [cgdb/cgdb#186]
I am using the latest cgdb in a terminal of a Amazon's Cloud9 IDE instance. When debugging a program with attached source code file, the code view (upper pane by default) only jump to the break point. If I hit `n`, the source view does not update the highlighted code line correspondingly. This does not happen when i run cgdb locally.

**Comment by idinwoodie** [comment]
@biocyberman thank you for bringing this to our attention. I will investigate the performance with Amazon's Cloud9 this coming week and will post a follow-up here.

**Comment by biocyberman** [comment]
@idinwoodie Just in case you didn't know, one can register and use C9 for free. You get root/sudo access to the install and therefore can install anything you want. I can also share my C9 instance for testing if that's more convenient for you.

**Comment by idinwoodie** [comment]
@biocyberman thanks for the heads up and the generous shared C9 offer. I should be all set to get squared away with C9 this week without any inconvenience. I'll tag you in a comment here if I'm having a hard time reproducing the setup.

**Comment by brasko** [comment]
I've got really no idea what to do with this case, so i'm going to close it.
If this issue is still an issue for you, and you'd like to walk me through the issue, I'll attempt to fix it for you before the next release.
