### ISSUE TITLE
inputrc enable-keypad messing with readline

### ISSUE THREAD

**Issue by dokthar** [cgdb/cgdb#190]
I am using a keyboard with a keypad and I have 'set enable-keypad on' in my .inputrc .
However when I launch cgdb I see the escape sequence '[?1h=' which correspond to keypad_xmit (aka smkx) termcap: ks.
I only have this problem with cgdb (not in gdb much like #189)

Running gdb
```
$ gdb
GNU gdb (GDB) 8.2
For help, type "help".
Type "apropos word" to search for commands related to "word"...
(gdb)
```

Running cgdb (only the output of the gdb window):
```
$ cgdb
[?1h=GNU gdb (GDB) 8.2
For help, type "help".
Type "apropos word" to search for commands related to "word"...
[?1h=(gdb)
```

Using 'set enable-keypad off' is not an option for me.

**Comment by brasko** [comment]
If I'm in a terminal and do 'set enable-keypad on' then launch cgdb, i do not reproduce the behavior.
cgdb works well.

Do you see this problem if you set the keypad from the terminal and then launch cgdb, or only when you have kepad enabled from the .inputrc?

Also, which version of cgdb are you using?

I'm wondering if cgdb is supposed to be looking for the keypad sequence if readline says it is enabled, and ignore the characters.... ?

**Comment by brasko** [comment]
Thanks, I was actually able to reproduce this.
I actually think there was an open case a year or two ago that might have been the same issue.
Neither I nor the reporter realized it was related to enable-keypad however.
I believe the fix will be quit simple, I've just got to get a few hours to put it together.
I'll keep you updated.

**Comment by brasko** [comment]
I'm still looking into this, there really isn't much documentation on what enable-keypad is. Hopefully I have something soon.

**Comment by brasko** [comment]
OK. I've read more about this. Readline manual says,
When set to ‘on’, Readline will try to enable the application keypad when it is called. Some systems need this to enable the arrow keys. The default is ‘off’. 

My question to you is, do you know if it would be acceptable for CGDB to simply ignore the enable and disable keypad escape sequences that readline is sending? If I can just ignore them, this may be relatively simple. If they need to be handled, and sent out as well to the terminal, it gets more complicated, as CGDB uses ncurses. At least I think it's more complicated. Do you know if it's OK just to ignore?

**Comment by brasko** [comment]
Could you please try the new-ui branch?

It should have resolved this issue for you. Please provide any feedback you can.

**Comment by dokthar** [comment]
With the new-ui branch I can see the prompt **correctly**, no more escape sequence.
Thanks !

**Comment by brasko** [comment]
Excellent! I have to clean a few more things up in the branch, and then I'll be doing a 0.8 release.
Let me know if you find any issues and I'll work on fixing them before the release.

**Comment by brasko** [comment]
Fixed in master
