### ISSUE TITLE
Ctrl - T doesn't seem to work (cgdb 0.7.0)

### ISSUE THREAD

**Issue by ghost** [cgdb/cgdb#193]
I am using cgdb 0.7.0. I  need  to send input to the program being debugged,but I found that [CGDB Manual [0.7.0]](https://cgdb.github.io/docs/cgdb.html) about send input to the program being debugged only say "TTY" with command ctrl - T,it seems about cgdb 0.6.7.
I see [cgdb 0.7.0 Changed - [GitHub]](https://raw.githubusercontent.com/cgdb/cgdb/v0.7.0/NEWS) :

* Remove the TTY mode and TTY window from CGDB. This previously allowed
    you to send input to the program being debugged through the TTY
    window in CGDB. It is better for the user to run their program in
    one terminal and attach to it with CGDB from another terminal in
    order to get terminal input and terminal output working correctly.

 * Add the -w command line option to CGDB. It directs CGDB to wait
    to start until either a debugger is attached to it, or until a key
    is written to it's stdin. This helps simplify debugging CGDB itself.

But I don't know how to use cgdb options: -w.
![selection_001](https://user-images.githubusercontent.com/17335099/47349186-a80bca80-d6e5-11e8-9419-bfea9a47f96b.png)
So can you explain how cgdb options: -w is used? Thank you very much.

**Comment by brasko** [comment]
Yes, the TTY option (Ctrl-T) was removed. Please let us know if this was useful to you previously.

I do have an action to replace this removed feature with something more usable.

The -w option only works on cgdb itself. It's goal is to allow you to attach a debugger to cgdb itself before all the startup code is completed in the main and the main loop is hit. This won't be useful to you for debugging your application. I'll update the documents and the command line help text to make this clear.

In general, I would recommend that if your program takes in input, start it in one terminal and attach to it from cgdb with another. You do this like, cgdb --pid=$(pidof YOURAPP). Then you can have full input/output of your program in it's own terminal and cgdb has all it's own controls in it's terminal.

Yes, this needs to get better.

**Comment by westrength** [comment]
In my opinion,the TTY option (Ctrl-T) is useful to send input to the program being debugged. Cgdb 0.6.7 has the TTY option,I think it's  a very good idea.I am sorry for that I don't know how cgdb --pid=$(pidof two-sum-scanf) is work.I tried it several times and failed.

![selection_002](https://user-images.githubusercontent.com/17335099/47598837-c10dc780-d9d4-11e8-971c-759be6535364.png)

**Comment by brasko** [comment]
You aren't the first person with this comment. I'm going to work on this feature next. Either adding back in Ctrl-T or coming up with another solution.

**Comment by westrength** [comment]
I am looking forward to it. Thanks  for your work.

**Comment by iurisegtovich** [comment]
dear developers

I am finding this program very practical and it was really interesting to be able to run it in the msys2/mingw lightweight setup for developing c/c++/fortran in windows (I usually work in linux but sometimes need to share work with collaborators in windows environments)

In my tests, I am having trouble with this tty stuff on msys2/mingw32

```
(gdb) start
Temporary breakpoint 1 at 0x437b9d: file MODEL_src/main.f90, line 1.
Starting program: C:\Users\iuri\Desktop\estimation\estimation_pkg\BUILDS\debug\bin\main.elf
warning: Warning: Failed to open TTY /dev/pty4, error 0x3. <-------TROUBLE HERE ----------------------------
[New Thread 3440.0xe30]

Temporary breakpoint 1, MAIN__ () at MODEL_src/main.f90:1
```

I thought this was a bug preventing me from opening the tty for input...
im using version 0.7.0, apparently

```
$ cgdb --version
CGDB 0.7.0
Copyright 2002-2010 Bob Rossi and Mike Mueller.
CGDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
There is absolutely no warranty for CGDB.
```

I got it from running `pacman -S cgdb` on the mingw32 mintty (msys2) terminal

I think it would be very useful to be able to start cgdb with default tty for input output being the same as the gdb window, as is the behavior when I run `gdb main.elf` - the gdb terminal stops accepting gdb input and waits for my input to the program being debugged. - I think this is a practical behavior for simple projects, and attaching or having an extra tty would be a more advanced use case.

thanks for your attention
best regards
iuri

**Comment by brasko** [comment]
Hi,

Please try the new-ui branch. The inferior pty is no longer set and I believe your issue may be resolved. Let me know.

**Comment by brasko** [comment]
I've pushed a change to master that should allow you to communicate with the debugged program the same way you would with cgdb as you do with gdb. Give it a shot. The tty window is no longer required.

**Comment by wenx-wang** [comment]
@brasko , can you directly let us know how can we  communicate with the debugged program. Thanks.

**Comment by brasko** [comment]
You'll need to build cgdb from git master and then you communicate with gdb as you normally would. Nothing special is required.

**Comment by wenx-wang** [comment]
Would it go into official release? It is not in cgdb0.7.1 currently.
