### ISSUE TITLE
readline inputrc commands vi-cmd-mode-string and vi-ins-mode-string produce garbage in cgdb prompt

### ISSUE THREAD

**Issue by gettylee** [cgdb/cgdb#195]
This is probably related to [issue 190](https://github.com/cgdb/cgdb/issues/190).

Adding these lines to inputrc causes the cgdb prompt to output "[2 q" or "[6 q" depending on vi mode instead of changing the cursor shape:
`set vi-cmd-mode-string "\1\e[2 q\2"`
`set vi-ins-mode-string "\1\e[6 q\2"`

This is observed in v0.7.0, master branch commit b88b697, and the current debian version (0.6.7).

Terminals tested: xterm 330, gvim 8.1-577 (in terminal mode)

**Comment by brasko** [comment]
If it's the same issue as issue 190 as you suggested, then you could also see if the new-ui branch resolves your issue.

Please provide any feedback.

**Comment by brasko** [comment]
I believe this is fixed now in master, as cgdb uses gdb's readline instead of it's own. Let me know if not.
