### ISSUE TITLE
[Error] cgdb sucked during make

### ISSUE THREAD

**Issue by Mon9oose** [cgdb/cgdb#201]
Hi I'm trying to build cgdb, but when i trying to "make" shell display error T^T

![스크린샷 2019-04-01 오후 2 52 38](https://user-images.githubusercontent.com/48558786/55306072-cd1f1900-548d-11e9-9736-f8dad0b636e2.png)

if you have any advise about that. feel free to comment for me
(using latest cgdb code by git clone https://github.com/cgdb/cgdb.git)

**Comment by honggyukim** [comment]
Hi @Mon9oose, I had the same problem. It's not merged yet but fixed in #198.

**Comment by Mon9oose** [comment]
Hi @honggyukim really thx your comment
I can fixed this error by your PR commit code :-)

![스크린샷 2019-04-01 오후 3 10 07](https://user-images.githubusercontent.com/48558786/55306795-60f1e480-5490-11e9-8941-8c2b881fb4da.png)

**Comment by honggyukim** [comment]
@Mon9oose Glad to hear that!

**Comment by idinwoodie** [comment]
@honggyukim @Mon9oose I will prioritize patch #198.

**Comment by honggyukim** [comment]
@idinwoodie Thanks!
