### ISSUE TITLE
Debugging a forking program fails on first run

### ISSUE THREAD

**Issue by p-h** [cgdb/cgdb#204]
Consider this program:
```
#include <stdio.h>
#include <unistd.h>

int main(void) {
    int pid = fork();

    if (pid == -1) {
        puts("Oops, failed");
    } else if (pid == 0) {
        puts("Hello from child");
    } else {
        puts("Hello from parent");
    }

    return 0;
}
```
if I open it in cgdb with:
```
break 10
set follow-fork-mode child
run
```
The first time I get:
```
Hello from parent
Thread 2.1 "main" received signal SIGHUP, Hangup.
```
If I rerun it, it works perfectly and the breakpoint gets hit. 

Can anyone reproduce this?

**Comment by brasko** [comment]
I just reproduced this. Let me see if I can find out why.

I've debugged plenty of programs that fork. I'm not sure what makes this one unique.

**Comment by brasko** [comment]
Can you please verify that this is fixed in the new-ui branch? It is fixed for me.

**Comment by brasko** [comment]
Fixed in master
