### ISSUE TITLE
Interpreation of Color codes in coredump

### ISSUE THREAD

**Issue by vlachoudis** [cgdb/cgdb#205]
It seems that new coredumps contain ansi-colored escape sequences in the traceback. Which looks nice in "gdb" but almost unreadable in cgdb.

**gdb**
![image](https://user-images.githubusercontent.com/3834594/57060008-02e73580-6cb8-11e9-97f4-30bead672ff9.png)

**cgdb**
![image](https://user-images.githubusercontent.com/3834594/57060014-0aa6da00-6cb8-11e9-827a-d496a52306cc.png)

**Comment by brasko** [comment]
Good news, you will be happy to know that cgdb 0.7.0 supports the newer gdb and core trumps. Give a try and let me know if there are still issues. Thanks!
