### ISSUE TITLE
cgdb can not use shell ;

### ISSUE THREAD

**Issue by yummyliu** [cgdb/cgdb#210]
cgdb
>> shell

it stuck when execute shell ...

![image](https://user-images.githubusercontent.com/4601177/63162391-fca57b00-c054-11e9-9767-7db54090382d.png)

**Comment by brasko** [comment]
It's not clear exactly why.

Please let us know your cgdb version, and then exact set of steps that lead
up to the issue.

I tried typing ":shell" in cgdb 0.7.1 and it dropped me to the shell fine.
Then I left the shell and went back to cgdb as expected.

Thanks,
Bob Rossi

**Comment by brasko** [comment]
After looking at this again
