### ISSUE TITLE
Newer GDB garbles output in CGDB debug window

### ISSUE THREAD

**Issue by dflogeras** [cgdb/cgdb#211]
It seems modern GDBs use color by default.  CGDB doesn't seem to be interpreting the escape codes, and they pollute anything in the debug window.  This is an annoyance, but it really breaks down when trying to open a new file.  Since the filenames themselves also have escape codes embedded in them, cgdb cannot open a file once it has been navigated to.  I tried:

`:set debugwincolor`

But that didn't seem to change the outcome for me.

I worked around this by just telling GDB to not use color.  I put the following in my .gdbinit file:

`set style enabled off`

Is there a more proper way to work with newer GDB?  Is there a way maybe cgdb can turn off color when invoking gdb, rather than globally turn it off (I usually only use GDB through CGDB but maybe not all users do, and wish to have color when running GDB plain).

Is there a plan to have CGDB interpret GDBs escape codes?

**Comment by brasko** [comment]
The newest version of cgdb supports this somewhat.

The colors from gdb are properly displayed.

However it doesn't always display the colors when it should.
This is something I'm actively looking into.

**Comment by dflogeras** [comment]
That's great to hear.  Let me know when you are to the point you need some testing/feedback.  Gentoo seems to have a live ebuild for cgdb so I can easily test off master if that helps out in any way.

**Comment by atotic** [comment]
with this patch, I can run with "set style enabled on" with no problems.

**Comment by brasko** [comment]
I'm going to close this issue as fixed since color output is supported in the latest cgdb. The only issue is that the backtrace is not colored because cgdb uses the output from GDB/MI which is not colored. I'm working on a concept for cgdb which uses the new-ui feature of GDB and that would bring colored support to the backtrace command as well.
