### ISSUE TITLE
Support for alternate '~/.cgdb' dir locations

### ISSUE THREAD

**Issue by yashlala** [cgdb/cgdb#212]
Hello!

When I use cgdb, it always creates a `~/.cgdb` directory directly under my home directory. 
There is no way to configure *where* cgdb puts this folder; it's hardcoded in to the application. 

Many applications follow XDG guidelines, putting their config/data directories in locations specified by the `XDG_CONFIG_HOME` and `XDG_DATA_HOME` environment variables (defaulting to `~/.config` and `~/.local/share`, respectively). Other applications use their own environment variables: GPG uses `GNUPGHOME`, etc.

I thought it would be nice if cgdb could do something similar, perhaps using the contents of envvar `CGDB_DIR`, then defaulting to '~/.cgdb' in order to not break existing behavior. I'm working on implementing this myself, and found myself wondering if there was any interest to get this feature into cgdb proper. Do you have any thoughts?

Apologies if this is the wrong place to discuss an issue; this is my first time trying to push code upstream. `CONTRIBUTING.md` indicated I should discuss the issues with the active maintainers, so I thought I might do that here.

**Comment by brasko** [comment]
Yes, I would be interested in moving that functionality into CGDB proper.

In cgdb.cpp:init_home_dir we determine the home directory.

Is that all that needs to change?
Would we have to update the documentation?

Thanks,
Bob Rossi

**Comment by yashlala** [comment]
Yes, the changes made are local to that method and associated documentation. I'll update the documentation this week before I send the pull request. 

However, adding this functionality seems to have exposed an bug in cgdb (as of version 20191012), where the program segfaults if the `~/.cgdb` directory/file doesn't have the right permissions. To replicate the bug, create a `~/.cgdb` file owned by root; the program will output: 
```
No such logger: 1
Could not create dir /home/lala/.cgdb
[1]    10198 segmentation fault (core dumped)  cgdb
```

The chances of root/another user creating a `~/.cgdb` file wasn't very high, but now that cgdb can use other folders, it would probably be prudent to fix this. A permissions check in `fs_util.cpp::fs_util_create_dir` should be enough to fix the problem; I can include the fix in the commit.

**Comment by brasko** [comment]
Sounds good and thanks!

**Comment by brasko** [comment]
Hi,

I just reviewed your patch (Yes, it's been a long time, sorry).

One thing I'm not sure about is if we should use CGDB_DIR or CGDB_HOME.
I need to see what other programs do or what seems most consistent.

The other issue that I think could be improved is the logging situation.
I think either we should modify clog.h to support enable/disable logging
or have a global for cgdb to support this, rather than make it fs_util.cpp
dependent.

I've reached out to the clog author to see if he likes the clog enable/disable
approach. I'll get back to you with that response.

**Comment by brasko** [comment]
All set, merged in your pull request. Try it out.

**Comment by brasko** [comment]
I just realized that while the ~/.cgdb directory is movable now by setting CGDB_DIR, what about the ~/.cgdbrc file?

Is this a major issue for you?

**Comment by yashlala** [comment]
CGDB doesn't seem to have ever used `~/.cgdbrc`; based on the documentation and my testing, CGDB only looks for `~/.cgdb/cgdbrc`. The new patch does move `~/.cgdb/cgdbrc` as expected. Unless I'm misunderstanding your question, I don't think there is an issue in terms of hardcoded filepaths. 

*CGDB Documentation (pre-change)*: 
> CGDB is capable of automating any of these commands through the use of the config file called 'cgdbrc'.  It looks in '$HOME''/.cgdb/' for that file.

*CGDB Source (cgdb/cgdb.cpp)*: 
```c
fs_util_get_path(cgdb_home_dir, "cgdbrc", config_file);
```

Regards, 

Yash Lala

**Comment by brasko** [comment]
You should be confused. I lost my mind for a moment. I had moved my ~/.cgdbrc to my home directory for testing this patch, and then assumed that was the location. Sorry about the confusion and thanks again!
