### ISSUE TITLE
Source window displays source that is out of date

### ISSUE THREAD

**Issue by atotic** [cgdb/cgdb#221]
My source window often displays a file that is out of date. After I step through it a few times, it'll update to new source.

There is a cgdb bug that is a pain point, but I am not sure where to start. If you can point me to "refresh the source file" logic code, I can try to fix it.

I use cgdb like this:
1. launch cgdb
2. compile and run
3. attach to running process with cgdb using "attach", find a problem
4. edit file, then go back to step 2.

I also see disassembly a lot when I hit a breakpoint. Source-only view comes back after stepping. This is #117 which is currently closed, any pointers on where to start appreciated.

**Comment by iandinwoodie** [comment]
> My source window often displays a file that is out of date. After I step through it a few times, it'll update to new source.

I have encountered this before and I believe I've use `Ctrl + l` (bash clear-screen) to refresh the source file. If you encounter this again, please attempt that combination to see if it refreshes the source file. While not a fix, it might be helpful to note a temporary workaround for others.

> There is a cgdb bug that is a pain point, but I am not sure where to start. If you can point me to "refresh the source file" logic code, I can try to fix it.

I think the function you want to investigate is the [`source_reload` function](https://github.com/cgdb/cgdb/blob/870e02df1af033d67cfcfaf5df704f5fe9051c88/cgdb/sources.h#L301).

> I also see disassembly a lot when I hit a breakpoint. Source-only view comes back after stepping. This is #117 which is currently closed, any pointers on where to start appreciated.

I have also seen this and have yet to investigate. It may stem from the breakpoint location given by `gdb`. In your case you have not issued `:set disasm`, correct?

**Comment by brasko** [comment]
Which version of CGDB are you using and is this reproducible?

BTW, have you set the auto source reload option in your .cgdbrc file?

We will need steps to reproduce the issue, otherwise we'll have to close it as
I can not reproduce this issue.

**Comment by atotic** [comment]
I am using custom-build  CGDB, my tree was at 8c2f3a2a632d63366eef419fabf3e8245d9b7a45,
Wed Feb 5 20:22:50 2020.

> have you set the auto source reload option in your .cgdbrc file

No, it should be on by default.

> We will need steps to reproduce the issue, otherwise we'll have to close it

No problem. 

If I run it it consistently, and is annoying enough, I'll fix it. It is good to know that it should work, and that I should set a breakpoint at source_reload to track the problem down. It has been sporadic so far, and rarely annoying.

Love cgdb! Thanks.

**Comment by atotic** [comment]
BTW, I also investigated the "I see disassembly a lot" problem.
Its a synchonization problem, and it happens something like this:
- hit a breakpoint of something that does not have a source.
- cgdb issues a disassembly command to gdb over the wire
- cont, and hit a new breakpoint
- proper source gets displayed briefly
- disassembly command comes back and you get disassembly

I hit it a lot in Chrome, because Chrome pauses on startup, waiting for SIGUSR. That pause triggers the disassembly....

**Comment by atotic** [comment]
I've modified my local tree to never display disassembly. I enjoy it, I always find disassembly jarring, and I have no use for it.

wdyt about a .dotfile setting to turn off disassembly? Would you take that patch?

**Comment by brasko** [comment]
A never display assembly mode seems fine to me, it's a good idea. Yes, a patch for that would make sense.

**Comment by brasko** [comment]
Yes, I would support a patch that disables disassembly altogether. If you have that, please open another case or pull request and I'll be happy to review.
