### ISSUE TITLE
Source line output appears in console output when using GDB 9.1

### ISSUE THREAD

**Issue by tylanphear** [cgdb/cgdb#223]
Using `cgdb` compiled from source @ [8c2f3a2](https://github.com/cgdb/cgdb/commit/8c2f3a2a632d63366eef419fabf3e8245d9b7a45), I now see source lines appear in the console output when `gdb` stops at a source line.

e.g.

```
Breakpoint 1, main (argc=1, argv=0x7fffffffc748) at Application.cpp:850
850           result = main_private(argc, argv);
(gdb)
```

Diffing the output of `gdb -ex "set annotate 2" --annotate=2` between the latest working version 8.3 and 9.1, this line appears most salient:

```
^Z^Zsource Application.cpp:850:28332:beg:0xd99950
+850          result = main_private(argc, argv);
```

It looks like `gdb` is now printing the actual contents of the source line along with the annotation, instead of just the annotation as before. This gets interpreted as output to the console just as any other data that follows an annotation.

This looks like a `gdb` bug. Probably it would be worth filing upstream. I know annotations have been deprecated for quite some time now, but even the latest 9.1 changelog contains the line `'thread-exited' event is now available in the annotations interface;`, so its possible they would consider fixing this. I don't see anything further in the changelog about this, so I assume this is an unintended regression caused by some other change down the line.

Otherwise, I think you might be able to fix this with a patch that does something like "don't output any lines between the `source` and `frame-end` annotation."

**Comment by tylanphear** [comment]
Did some digging in the sourceware repo. It looks like this change was made intentionally in [this commit](https://github.com/bminor/binutils-gdb/commit/ec8e2b6d3051f0b4b2a8eee9917898e95046c62f) entitled "Don't allow annotations to influence what else GDB prints". This is responsible for the printing of source line info. It could potentially have implications for other annotations.

**Comment by brasko** [comment]
Thanks Tyler. I sent an email to the gdb mailing list about this.                                                                    
It does seem like a bug in gdb. Lets see what they say.                                                                              
                                                                                                                                     
The ultimate solution is switching to GDB/MI and perhaps I should                                                                    
find time to do that sooner rather than later.

**Comment by brasko** [comment]
An update on an email I sent to gdb mailing list:

 Ironically, I just upgraded CGDB to no longer use annotations.
I'm moved it from annotations to gdb/mi, in the same way that
Eclipse uses MI, by using the new-ui feature of gdb. Now i see the
source linse are still visible in the console. gdb doesn't know
to not show them in this mode.

To recap,
 - cgdb using annotations does not show code in console
 - cgdb using mi using new-ui does show code in console
 - gdb tui does not show code in console
 - eclipse probably shows code in console, as it uses mi and new-ui

Would it be to much to ask that if new-ui is being used, that we
assume a front end is being used, and not display the code in the console?

**Comment by brasko** [comment]
The GDB community thinks it would be best for a new option to be added to GDB to suppress this line.

I won't have the time to add this new option in the immediate future.
So this will be the default behavior until someone gets around to that.

**Comment by brasko** [comment]
I submitted a patch for this today,
https://sourceware.org/pipermail/gdb/2024-May/051339.html
Lets see what they say.
