### ISSUE TITLE
Colored output is not working

### ISSUE THREAD

**Issue by changbindu** [cgdb/cgdb#224]
$ cgdb -d gdb-multiarch vmlinux

The out of cgdb become this:

$4 = [34m0xffff00003a564080[m "r"
(gdb) p devname 
$5 = [34m0xffff00003a57ab00[m "/dev/root"
(gdb) bt
#0  [33mp9_virtio_create[m ([36mclient[m=0xffff00003a574d00, [36mdevname[m=0xffff00003a57ab00 "/dev/root", [36margs[m=<optimized out>) at [32mnet/9p/trans_virtio.c[m:663
#1  [34m0xffff800010c13f38[m in [33mp9_client_create[m ([36mdev_name[m=0xffff800011396a88 <p9_virtio_drv> "`\n\004\021", [36moptions[m=0xffff00003a57ab00 "/dev/root") at [32mnet/9p/client.
c[m:1039
#2  [34m0xffff8000104eb6d0[m in [33mv9fs_session_init[m ([36mv9ses[m=0xffff00003a574d00, [36mdev_name[m=0x0, [36mdata[m=0xffff800011433018 <virtio_chan_list> "@\260V:") at [32mfs/9p/v9fs.c
[m:406
#3  [34m0xffff8000104e687c[m in [33mv9fs_mount[m ([36mfs_type[m=<optimized out>, [36mflags[m=289615896, [36mdev_name[m=0xffff00003a57ab00 "/dev/root", [36mdata[m=0xffff00003aced000) at [32
mfs/9p/vfs_super.c[m:124
#4  [34m0xffff8000103301fc[m in [33mlegacy_get_tree[m ([36mfc[m=0xffff00003a57ab00) at [32mfs/fs_context.c[m:622
#5  [34m0xffff8000102eb29c[m in [33mvfs_get_tree[m ([36mfc[m=0xffff00003aced000) at [32mfs/super.c[m:1547
#6  [34m0xffff80001031647c[m in [33mdo_new_mount[m ([36mdata[m=<optimized out>, [36mname[m=<optimized out>, [36mmnt_flags[m=<optimized out>, [36msb_flags[m=<optimized out>, [36mfstype[m=<o
ptimized out>, [36mpath[m=<optimized out>) at [32mfs/namespace.c[m:2822
#7  [33mdo_mount[m ([36mdev_name[m=0xffff800010f56050 "/dev/root", [36mdir_name[m=<optimized out>, [36mtype_page[m=<optimized out>, [36mflags[m=32768, [36mdata_page[m=0xffff00003aced000) a
t [32mfs/namespace.c[m:3107
#8  [34m0xffff800011121874[m in [33mdo_mount_root[m ([36mname[m=0xffff800010f56050 "/dev/root", [36mfs[m=0xffff00003acee000 "9p", [36mflags[m=32768, [36mdata[m=0xffff800011396bd8 <virtio_9
p_lock>) at [32minit/do_mounts.c[m:408
#9  [34m0xffff800011121a78[m in [33mmount_block_root[m ([36mname[m=0x8000 <error: Cannot access memory at address 0x8000>, [36mflags[m=32768) at [32minit/do_mounts.c[m:441
#10 [34m0xffff800011121cdc[m in [33mmount_root[m () at [32minit/do_mounts.c[m:631
#11 [34m0xffff800011121e44[m in [33mprepare_namespace[m () at [32minit/do_mounts.c[m:690
#12 [34m0xffff800011121660[m in [33mkernel_init_freeable[m () at [32minit/main.c[m:1460
#13 [34m0xffff800010c36990[m in [33mkernel_init[m ([36munused[m=<optimized out>) at [32minit/main.c[m:1352
#14 [34m0xffff800010085700[m in [33mret_from_fork[m () at [32march/arm64/kernel/entry.S[m:909
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

$ cgdb -v
CGDB 0.6.7
Copyright 2002-2010 Bob Rossi and Mike Mueller.
CGDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
There is absolutely no warranty for CGDB.

$ gdb-multiarch -v
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by brasko** [comment]
If you update to a newer CGDB this should be fixed. Please respond back if not.

**Comment by changbindu** [comment]
Thanks, the new version works well.
