### ISSUE TITLE
Chinese support in LinuxMint error

### ISSUE THREAD

**Issue by leeyiw** [cgdb/cgdb#23]
I have recently use LinuxMint and installed CGDB by command:

```
apt-get install cgdb
```

and CGDB version 0.6.6 is installed. But when I try to debug my program with Chinese comment, CGDB shows wrong Chinese charaters in the code window:

![image](https://f.cloud.github.com/assets/3157740/469802/ceca734a-b6e0-11e2-8dda-004a82c247f8.png)

and I open the gdb to debug it, and it goes all right:

![image](https://f.cloud.github.com/assets/3157740/469811/034dee9e-b6e1-11e2-92e1-6b2fe4334d13.png)

and my locale is:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

also I tried to set LC_ALL to "C" or "zh_CN.UTF-8" or "", It doesn't work.
But CGDB in Ubuntu 10.04 and 12.04 don't have this problem.

**Comment by DarcySail** [comment]
i do the same thing as leeyiw, but this solution doesn't work for me.
I think maybe this isn't cgdb' fault but gdb's. when i print "l" in gdb, everything works fine,  when i turn to "gdb -tui", Garbled also occur in TUI window.
