### ISSUE TITLE
Can I use mouse to drag and drop window border?

### ISSUE THREAD

**Issue by zchrissirhcz** [cgdb/cgdb#231]
Hi, thanks for providing this efficiency tool.

I'd like to know if I can customize each window's size, of the source and debug window.

Right now I just put those in my `cgdbrc`:
```bash
set ignorecase
set ts=4
set wso=vertical
set eld=shortarrow
set hls
map <F9> :until<cr>
```

And cgdb version is the lastest from github, built from source.

**Comment by brasko** [comment]
You can move the windows only with the keyboard shortcuts.
-    Shrink source window 1 line or column (depending on split orientation).
=    Grow source window 1 line or column (depending on split orientation).
_    Shrink source window 25%
+    Grow source window 25%

You can not use the mouse at the moment, although it's a good idea.
