### ISSUE TITLE
ncurses: configure error

### ISSUE THREAD

**Issue by liquanfeng** [cgdb/cgdb#232]
`configure: error: cgdb needs ncurses/curses to build. ncurses is strongly recommended.
            If your system does not have ncurses get it!
            If that is not an option try 'configure --with-curses.'
            You can try --with-ncurses=/foo/ncurses to tell configure where ncurses is.
`
when i build cgdb, i meet this problem with command as follow:
`cgdb-0.7.1/build$ ../configure --with-readline=../../readline-8.0/shlib/libreadline.so.8.0 --with-ncurses=../../ncurses-6.2/lib/libncurses.so.6
`
Notice: I am not sudoers, so I have to build ncurses by myself.
help please. i love cgdb!

**Comment by lovelyvirus** [comment]
@liquanfeng How did you solve this issue?
