### ISSUE TITLE
Patch for ANSI escape issues with GDB-9

### ISSUE THREAD

**Issue by gergap** [cgdb/cgdb#239]
Hi

I had issues with GNU gdb (Debian 9.2-1) 9.2 on Debian Testing.
GDB has added new ansi escape sequence.
The colors stuff is already handled by cgdb on master,
but still there are other sequences like e.g. "[?1l,[?1h,=,>" that are not handled and produce garbage in the output.
See http://ascii-table.com/ansi-escape-sequences-vt-100.php for a description of those sequences.

I created a small patch which simply ignores those sequences. I don't say this is perfect, but works for me.
It's at least an improvement.

Attached you find a patch created on latest master.

[0001-ignore-some-new-gdb-ansi-escape-sequences-to-avoid-g.patch.gz](https://github.com/cgdb/cgdb/files/5310772/0001-ignore-some-new-gdb-ansi-escape-sequences-to-avoid-g.patch.gz)

**Comment by gergap** [comment]
btw, the current parsing code uses `buf[j + 1]` which could read more than buflen data, which could load to an access violation IMO. I didn't fix this in my patch and used the same approach.

**Comment by gergap** [comment]
Ok, I could not leave it as is and added a buffer length check for my new code (1st patch) and the existing code (2nd patch).
Attached there are two new patches superseding the previous one.
[patches.tar.gz](https://github.com/cgdb/cgdb/files/5310854/patches.tar.gz)

**Comment by brasko** [comment]
Thanks, I'll have to check this out when I find some time to move cgdb forward.

Did you sign the patches? That way I can include them in the release after review.

**Comment by gergap** [comment]
here are the patches again with signed-off-by info
[patches.tar.gz](https://github.com/cgdb/cgdb/files/5355949/patches.tar.gz)

**Comment by brasko** [comment]
OK. I'm getting ready to do a release soonish. I'll make sure to review this before that happens.

**Comment by brasko** [comment]
I've reviewed this and will integrate it. However, I would love if you could give me a reproducer.

I can't seem to get those key codes to come out of gdb for testing.

**Comment by brasko** [comment]
I've committed your changes, thanks for providing the patches
