### ISSUE TITLE
Colour missing in backtraces

### ISSUE THREAD

**Issue by pwaller** [cgdb/cgdb#242]
Reproduced on master cgdb + master gdb.

#### Steps to reproduce:

1. With modern gdb, run `cgdb -- -ex starti -ex bt echo`.
2. Observe coloured backtrace already present in terminal at the first instruction of `/bin/echo`.
3. Run `bt`.
4. Observe most recent backtrace is lacking colour.

#### Background -- (it's not exactly a cgdb issue)

I've traced this back to a bug in gdb, which you can reproduce with the following:

```
gdb -ex starti -ex bt -ex 'interpreter-exec mi echo' -ex bt -ex q echo <<<''
```
It turns out that running an `interpreter-exec mi` breaks the colour interface. The reason is that `mi_interp::resume` rewires `gdb_stdout` such that `stdio_file::can_emit_style_escape` now returns false because `this == gdb_stdout` no longer holds. Nothing puts `gdb_stdout` back how it was after the `interpreter-exec` finishes.

I've got [a patch](https://sourceware.org/pipermail/gdb-patches/2020-October/172584.html) [0] which I'm submitting to gdb-patches and I'm leaving a breadcrumb here for anyone else who finds the same issue. (Hello, future me, what are you doing here again?)

Since this isn't strictly a cgdb bug I don't mind whether the issue remains open here or not. I'll try and report back if I see the problem is fixed upstream.

[0] [[PATCH] gdb: Preserve gdb_std{out, err, ...} across interpreter-exec mi](https://sourceware.org/pipermail/gdb-patches/2020-October/172584.html)

**Comment by pwaller** [comment]
Fix landed in https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=e1ff6226d8e36896edbdd651753a3e1292381ba0

**Comment by brasko** [comment]
Wow, Thanks Peter, very impressive. I'm sure many people will benefit from this if it is accepted upstream!

**Comment by pwaller** [comment]
It has landed in gdb master (see link in above comment for commit), so it has been accepted. Don't know about gdb's release schedule though. It might not be available till gdb 11.
