### ISSUE TITLE
[ubuntu20.04] [0.7.* version] press T, it cannot open  I/O window

### ISSUE THREAD

**Issue by dapao1988** [cgdb/cgdb#244]
1. environment: 20.04 
2. issues:
0.6.7 and 0.6.8 version: it can open I/O window for input some inital value, but it cannot recognize color in gdb window when print values;
0.7.0 and 0.7.1 version: it can recognize colors when print values, but I cannot open I/O  window when press T; Therefore I have no idea about way to input some stdin values

It confuses me.
waiting for some answer , thanks!

**Comment by brasko** [comment]
Please try out the new-ui branch.

You can now send input to gdb the same way would if you were not using cgdb.

**Comment by brasko** [comment]
Fixed in master, an I/O window is no longer necessary, you can send input just like when using gdb.
