### ISSUE TITLE
Wrong key code when Ctrl-a, Ctrl-e

### ISSUE THREAD

**Issue by WilliamLeoV** [cgdb/cgdb#245]
GDB a process of cgdb, set breakpint on if_input(). When input Ctrl-A，the “key” parameter of if_input is 10005, and Ctrl-e is 10006. But according to “enum cgdb_key” in ./lib/kui/kui_cgdb_key.h，they should be 10023 and 10027. 
The Ctrl-B, Ctrl-D.... are right.

**Comment by brasko** [comment]
Hi William,

Sorry it took so long to respond. I'm preparing a release after I review most of the open issues.

I could not reproduce this issue. So here are a few questions.

Do you have anything special in your ~/.cgdb/cgdbrc regarding mappings?
Do you have anything special in your readline configuration? /etc/input (cgdb reads this and honors the mappings)

If you run ./lib/kui/kui_driver
and then type ctrl-a, ctrl-b, etc, do you get the proper response? For me it's this:
(kui) CGDB_KEY_CTRL_A[1]
(kui) CGDB_KEY_CTRL_B[2]
(kui) CGDB_KEY_CTRL_C[3]
(kui) CGDB_KEY_CTRL_D[4]
(kui) CGDB_KEY_CTRL_E[5]
(kui) CGDB_KEY_CTRL_F[6]

**Comment by brasko** [comment]
William, please reopen if this is still an issue for you and you can reproduce it for me. Thanks!
