### ISSUE TITLE
The cgdb display needs to update its contents when gdb braches control to exec. 

### ISSUE THREAD

**Issue by mortdeus** [cgdb/cgdb#25]
This isnt really a critical bug persay, but it would be nice to have the new source file shown in the cgbd display right after a call to exec with  the 'follow-exec-mode same' option set. Currently we have to drop to gdb's CLI and set a breakpoint on main to update the display to show the new source file.

**Comment by leeyiw** [comment]
I also prefer CGDB auto update the display when `exec` happens.

**Comment by mikesart** [comment]
Closing really old bugs. If this still is a problem / request, please open a new bug. Thanks much.
