### ISSUE TITLE
Incorrect display of utf-8 strings in gdb command window

### ISSUE THREAD

**Issue by deeptho** [cgdb/cgdb#250]
With cgdb-0.6.8-16.fc33.x86_64 (latest fedora33 rpm):

The attached program 
[x_c.txt](https://github.com/cgdb/cgdb/files/6145121/x_c.txt)
contains a unicode string x. This prints correctly using regular gdb:

`gdb /tmp/x
...
print x
$1 = "Débats, reportages et interventions d'experts permettent d'approfondir l'actualité du jour."
`

in cgdb, the accented characters are dropped:
`cgdb /tmp/xgdb) print x
$1 = "Dbats, reportages et interventions d'experts permettent d'approfondir l'ac
tualit du jour."
(gdb) 
`

Command like  'set charset UTF-8' have no effect as that charset is already the default (for me)

**Comment by brasko** [comment]
Using cgdb from 0.6.8,
(gdb) print x
$1 = "Dbats, reportages et interventions d'experts permettent d'approfondir l'ac
tualit du jour."



Using cgdb from master,
(gdb) print x
$1 = "Débats, reportages et interventions d'experts permettent d'approfondir l'
actualité du jour."

Just update and you should be good to go.
