### ISSUE TITLE
GDB console does not display color

### ISSUE THREAD

**Issue by Sholde** [cgdb/cgdb#251]
Hi,

I love **cgdb**, tanks for this front-end.
I have a little problem of display when I set a breakpoint.
A new line is inserted before the sentence:
```c
(gdb) b main

Breakpoint 1 at 0x1168: file test.c, line 6.(gdb)
```

I use **gdb 10.1** and have **cgdb 20200728**.

Thanks,

**Comment by brasko** [comment]
You can please try this with the latest build from master, a lot has changed.

Also, how are you setting the breakpoint? by hitting the space bar?

**Comment by Sholde** [comment]
> You can please try this with the latest build from master, a lot has changed.

The latest build from master fix my problem but I don't have color for gdb console. I don't know if due to my terminal because I saw last issues which talking about that (like #129) but I use **xfe4-terminal**.

> Also, how are you setting the breakpoint? by hitting the space bar?

I just press:
```
b<space>main<enter>
```
Like normal way.

**Comment by Sholde** [comment]
![cgdb_color](https://user-images.githubusercontent.com/47916105/112527454-5af31d80-8da3-11eb-9825-c6e40f9c8ebc.PNG)

**Comment by brasko** [comment]
Thanks for reporting this, I've pushed an experimental fix. Please let me know if it works for you.

**Comment by Sholde** [comment]
Yes it fix color problem.
But now I have ANSI escape code like : 04h
I just follow the issue #189 and it fix the new problem adding `set enable-bracketed-paste off` in `~/.inputrc`.

**Comment by Sholde** [comment]
I think we can close the issue.

**Comment by brasko** [comment]
I had to revert the change that fixed this issue as it created other issues. I'm reopening this case.

**Comment by brasko** [comment]
I've finally made some progress on integrating cgdb with libvterm.
@Sholde  Could you please build cgdb from the libvterm branch and let me know if it resolves all the issues found above?

**Comment by auouymous** [comment]
Color in gdb output works for me with libvterm.

**Comment by Sholde** [comment]
I don't use cgdb anymore. But I installed libvterm and recompiled cgdb and it gave me this:
![cgdb_test_libvterm](https://user-images.githubusercontent.com/47916105/131257333-35d88a9c-7b85-412c-bc3f-5dea85a47bbb.PNG)

**Comment by brasko** [comment]
I've integrated the libvterm branch into master. This should have fixed this issue. Please let me know otherwise. Thanks!
