### ISSUE TITLE
Please consider making a release

### ISSUE THREAD

**Issue by yurivict** [cgdb/cgdb#253]
Last release was in Aug 2019 - a long time ago.

**Comment by joachim-reichel** [comment]
Yes, I'd also like to see a new release with all these bug fixes and improvements. Thanks!

**Comment by brasko** [comment]
Yes, we'll make a release as soon as I get pull request #237 done.
I'd also like to investigate issue #251 more.
I'd also like to review the remaining issues and pull requests one last time and test cgdb out a little more.
Then we'll make a release.

**Comment by dflogeras** [comment]
I've been playing around with master on Gentoo all day and it looks good to me.   Thanks for the push, I look forward to using it more!

**Comment by brasko** [comment]
There are three issues left to close before a release. Issue #293 which may be a user error, issue #291, which i'm hoping to get steps to reproduce, and pull request #295 which I reviewed tonight and emailed the author for ideas on how to move forward.

**Comment by brasko** [comment]
Done! cgdb 0.8.0 is officially released.

**Comment by honggyukim** [comment]
Great! Thanks very much for the release :)

**Comment by yurivict** [comment]
Thank you!
