### ISSUE TITLE
cgdb prints '[?2004h' in xfce4 terminal

### ISSUE THREAD

**Issue by yurivict** [cgdb/cgdb#256]
Every line is prepended with ```[?2004h```, see below.
Cursor also jumps unnaturally when user hits "Backspace" on previously entered commands.

```
[yuri@yv /tmp]$ 
[yuri@yv /tmp]$ 
[yuri@yv /tmp]$ 
[yuri@yv /tmp]$ cgdb ./a.out 





                                                                                                      _|  _|      
                                                                              _|_|_|    _|_|_|    _|_|_|  _|_|_|  
                                                                            _|        _|    _|  _|    _|  _|    _|
                                                                            _|        _|    _|  _|    _|  _|    _|
                                                                              _|_|_|    _|_|_|    _|_|_|  _|_|_|  
                                                                                            _|                    
                                                                                        _|_|                      

                                                                                      a curses debugger
                                                                                        version 0.7.1

                                                                           type  q<Enter>            to exit      
                                                                           type  help<Enter>         for GDB help 
                                                                           type  <ESC>:help<Enter>   for CGDB help






                                                                                                                                                                                             *
[?2004hGNU gdb (GDB) 10.1 [GDB v10.1 for FreeBSD]
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-portbld-freebsd12.2".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./a.out...
[?2004h(gdb) up
[?2004lNo stack.
[?2004h(gdb) down
[?2004lNo stack.
[?2004h(gdb) 
```

**Comment by joachim-reichel** [comment]
This is the same problem as #255. You see "[?2004h" instead of "40h" since your version does not have the fix for #239.

**Comment by brasko** [comment]
Can you please let me know if you still see this issue? I'm wondering if a14258d helped at all.

**Comment by joachim-reichel** [comment]
It fixes the issue for me, but the colors are also gone (as expected).

**Comment by brasko** [comment]
thanks for reporting this. I see it's a common issue.

The goal is to implement a virtual terminal like neovim using libvterm.
It's going to take me a while to figure this out, but if it works out, should be the best of all options.

**Comment by brasko** [comment]
I've finally made some progress on integrating cgdb with libvterm.
@yurivict , @joachim-reichel , @Cons-Cat  Could you please build cgdb from the libvterm branch and let me know if it resolves all the issues found above?

**Comment by yurivict** [comment]
The ```libvterm```  branch fails to build:
```
./configure: RL_LIB_READLINE_VERSION: not found
configure: error: CGDB requires GNU readline 5.1 or greater to link.
  If you used --with-readline instead of using the system readline library,
  make sure to set the correct readline library on the linker search path
  via LD_LIBRARY_PATH or some other facility.
===>  Script "configure" failed unexpectedly.
Please report the problem to serio.jeffrey@gmail.com [maintainer] and attach
the "/disk-samsung/freebsd-ports/devel/cgdb/work/cgdb-dc15e18/config.log"
including the output of the failure of your make command. Also, it might be
a good idea to provide an overview of all packages installed on your system
(e.g. a /usr/local/sbin/pkg-static info -g -Ea).
```

It doesn't print any other explanation.
I have GNU readline-8.1.1 installed.

**Comment by brasko** [comment]
If you install readline-dev that will probably do it. You most likely only have the readline user libraries installed and not the header files.

**Comment by yurivict** [comment]
> You most likely only have the readline user libraries installed and not the header files.

No, on FreeBSD they are always together.
It tries to run RL_LIB_READLINE_VERSION as an executable.

**Comment by MaxSagebaum** [comment]
I had the same problem on Fedora 34 (5.13.9-200.fc34.x86_64).

I compiled and tried the libvterm branch and it worked like a charm. Also looks good on the colors.

Sidenote: Pasting 200 characters into the terminal took quite long (like 2 or 3 seconds) you could see how every character is added manually. Otherwise the performance was ok. (I did not recognize any other hickups.)

**Comment by joachim-reichel** [comment]
The garbage in the output is gone. But I'm a bit unsure how much colored output I should see. I have colors only in the first "GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git" line and for the filename in "Reading symbols from <file>", not for the GDB prompt. Looking at the screenshot from the 1st message in this issue, I presume the GDB prompt and the reply "No stack" should also be colored, or am I wrong there?

**Comment by brasko** [comment]
@joachim-reichel The coloring should be the same in cgdb as it is with just plain gdb. Is that the case? Let me know. Thanks!

**Comment by brasko** [comment]
@MaxSagebaum thanks for pointing out that i need to test performance. I probably wouldn't have.

**Comment by auouymous** [comment]
@brasko Does this support bracketed paste (not working) or simply hide the escape sequence?

I also experience the slow pasting. But pasting enough text causes it to wrap around and overwrite the prompt, as if the terminal is only 44 characters wide, no matter what the actual width is. Pasting the GPL license line from gdb output wraps after the '<', and backspacing the entire line causes the prompt to move to previous line.

**Comment by joachim-reichel** [comment]
@brasko Yes, the coloring is as in gdb, all good!
