### ISSUE TITLE
Implement commands that allows us to map the built in cgbd mode hotkeys. 

### ISSUE THREAD

**Issue by mortdeus** [cgdb/cgdb#26]
How can we directly swap a hotkey's function with another key that doesnt have a callable ex mode command? (this is assuming the manual shows all available commands). 

For example swapping n, N's search function with j's movement function? 

As somebody who uses the colemak keymap, many of the already assigned hotkeys are my movement keys and I have no option but to just override the functions. Which sucks.

So you can get a better idea of what im talking about here is my hotkey config and the colemak layout
. 
http://ix.io/5Qp .
http://colemak.com/wiki/images/8/80/Colemak_layout_2.png

**Comment by mikesart** [comment]
Closing really old bugs. If this still is a problem / request, please open a new bug. Thanks much.
