### ISSUE TITLE
breakpoint operations stop working after F5 or F6 or F7 or F8 or F12

### ISSUE THREAD

**Issue by focus64** [cgdb/cgdb#260]
With the latest git version, after pressing F5 or F6 or F7 or F8 or F10 in cgdb mode, the following breakpoint operations stop working.

1. hitting space key or 't' in cgdb mode would have no effect (neither line number marks shown in the main source window, nor breakpoints set in gdb)
2. break/delete/disable/clear breakpoints in gdb mode would not show (or erase) corresponding line number marks in the main source window

**Comment by brasko** [comment]
I can't reproduce this behavior. Can you send in the .cgdb log files to see if I can find anything interesting?

**Comment by focus64** [comment]
Log files in .cgdb:
[cgdb_log1.txt](http://0x0.st/-jDt.txt)
[cgdb_gdb_console_io_log1.txt](http://0x0.st/-jDv.txt)
[cgdb_gdb_mi_io_log1.txt](http://0x0.st/-jDx.txt)

I observed this behavior on my fedora and archlinux systems. On archlinux, I tried cgdb-git in AUR.

**Comment by brasko** [comment]
Thanks for the log files, I'll try to follow up on this soon.

**Comment by bmorel** [comment]
Hi have similar problem since I upgraded to current debian stable (bullseye). cgdb also sometimes fall into an infinite loop (uses 100% CPU and becoming unresponsive). This really started with debian 11 (debian 10 did not had this problem) so I think this may be related to:

```
% gdb --version 
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
```

More specifically, the 1st breakpoint works, but then all seems broken.

**Comment by brasko** [comment]
Is this also true with git master?

**Comment by brasko** [comment]
I just installed gdb-10.1 and still can't reproduce.
I think this issue is related to #260 and I'd love to track it down before the next release.
Is there any other assistance that can be provided?

**Comment by brasko** [comment]
I've reproduced this issue. Excellent. I'll have it fixed soon I hope.

**Comment by brasko** [comment]
I believe I fixed this issue. Please let me know if this can be verified. If not, I'll reopen.

Thanks for reporting this!
