### ISSUE TITLE
"set selectedlinedisplay" doesn't work

### ISSUE THREAD

**Issue by ravenxrz** [cgdb/cgdb#267]
I install cgdb 0.6.8 on centos 7, but it's difficult to locate where my cursor is. Then I try to use "set selectedlinedisplay=highlight" command to change the style of the current line cursor, and it doesn't work. 

![image](https://user-images.githubusercontent.com/44746032/123897141-7a4aa980-d995-11eb-9583-86fae7546ca7.png)

As you can see, the only way to find where I am is the bold line number(which is 491 in this case). Is there any way to fix this?
Thanks in advance。

**Comment by auouymous** [comment]
In `$HOME/.cgdb/cgdbrc` add a line containing `hi SelectedLineNr ctermfg=<color> ctermbg=<color> cterm=<attribute>`, where color is 0-15 or a name such as Blue or DarkBlue, and attribute is bold, reverse, underline, or a combination of those separated by a comma. Look in /usr/share/cgdb/cgdb.txt for all color names, attributes and UI and syntax elements that can be colored. Colors that don't begin with "Dark" are naturally bold as well.

**Comment by ravenxrz** [comment]
> In `$HOME/.cgdb/cgdbrc` add a line containing `hi SelectedLineNr ctermfg=<color> ctermbg=<color> cterm=<attribute>`, where color is 0-15 or a name such as Blue or DarkBlue, and attribute is bold, reverse, underline, or a combination of those separated by a comma. Look in /usr/share/cgdb/cgdb.txt for all color names, attributes and UI and syntax elements that can be colored. Colors that don't begin with "Dark" are naturally bold as well.

Thank you. It's much better now.
