### ISSUE TITLE
Does `cgdb` support different themes/color schemes?

### ISSUE THREAD

**Issue by Logarithmus** [cgdb/cgdb#268]
I'd like to use e. g. monokai or gruvbox as a color scheme for source code. How can I do this?

**Comment by auouymous** [comment]
Yes, see https://github.com/cgdb/cgdb/blob/master/doc/cgdb.texi#L950.

```
hi Comment    ctermfg=DarkBlue    ctermbg=Black    cterm=normal
```

Attributes and colors can be found immediately after the highlighting options.

**Comment by Logarithmus** [comment]
@auouymous thanks, I'll check it out.
