### ISSUE TITLE
Configure error when cross-compiling

### ISSUE THREAD

**Issue by tangm421** [cgdb/cgdb#270]
When I use a cross compiler to compile cgdb on ubuntu16.04.3, configure reports an error at the end：
`checking for /dev/ptmx... configure: error: cannot check for file existence when cross compiling`

I have compiled the dependent library libncurses.a, and specified the header and library path using CPPFLAGS and LDFLAGS。
Is my command wrong or do I need to set some compilation option?
`./configure --host=arm-hisiv400-linux CPPFLAGS="-I../ncurses-6.0/include" LDFLAGS="-L../ncurses-6.0/lib"`

**Comment by brasko** [comment]
I haven't cross compiled cgdb before, I suppose I don't know exactly how you would do this.

Does the target machine have ptmx, if so, i suppose you should set that ability in autoconf before it makes the check?

**Comment by tangm421** [comment]
> I haven't cross compiled cgdb before, I suppose I don't know exactly how you would do this.
> 
> Does the target machine have ptmx, if so, i suppose you should set that ability in autoconf before it makes the check?

I'm not sure I actually understand what you mean 😕  **set that ability in autoconf before it makes the check**

`/dev/ptmx` `/proc/self/status` These files are available on the target platform, but not exist on build machine or cross-compilation development package, So it always reports an error during configuration. Maybe this library does not support cross compilation？

**Comment by brasko** [comment]
I don't cross compile cgdb, but would be ok if a patch was submitted to make it cross compilable.
I'll close this , but if you want to reactivate and discuss cross compilation, that's fine.
