### ISSUE TITLE
A potential bug of memory leak

### ISSUE THREAD

**Issue by ash1852** [cgdb/cgdb#271]
hello , I found a potential bug of memory leak in source code,would you help me check if this bug is true?thank you very much

step  1 : 
	 In file  lib/util/sys_util.c , function  cgdb_strdup   line  64 :
 		 Allocate memory to t 

step  2 : 
	 In file  lib/util/sys_util.c , function  cgdb_strdup   line  66 :
 		 Select the true branch at this point (t!=null is true) 

step  3 : 
	 In file  cgdb/cgdbrc.c , function  command_parse_unmap   line  852 :
 		 Function cgdb_strdup executes and stores the return value to key_token 

step  4 : 
	 In file  cgdb/cgdbrc.c , function  command_parse_unmap   line  855 :
 		 Select the false branch at this point (val==(-1) is false), the allocated memory is leaked

**Comment by brasko** [comment]
This is not a bug. The memory is clearly freed in step 4.
