### ISSUE TITLE
Several potential bugs of Unchecked Return Value to NULL Pointer Dereference

### ISSUE THREAD

**Issue by ash1852** [cgdb/cgdb#272]
hello,I found some potential bugs of Unchecked Return Value to NULL Pointer Dereference,would you help me check whether these bugs are true?thank you very much.

==============================================================================

step  1 : 
	 In file  lib/util/pseudo.c , function  groupname2gid   line  132 :
 		 Function fopen executes and stores the return value to group (group can be null) (lacking failure check, 6 out of 12 file openings checked failures) 

step  2 : 
	 In file  lib/util/pseudo.c , function  groupname2gid   line  136 :
 		 group is used as the 3rd parameter in function fgets (group can be null) 

==============================================================================

step  1 : 
	 In file  lib/util/pseudo.c , function  uid2gid   line  152 :
 		 Function fopen executes and stores the return value to passwd (passwd can be null) (lacking failure check, 6 out of 12 file openings checked failures) 

step  2 : 
	 In file  lib/util/pseudo.c , function  uid2gid   line  156 :
 		 passwd is used as the 3rd parameter in function fgets (passwd can be null) 

==============================================================================

step  1 : 
	 In file  lib/kui/kui_term.c , function  kui_term_get_keycode_from_cgdb_key   line  432 :
 		 Select the false branch at this point (cgdb_keycodes[i].key!=CGDB_KEY_ERROR is false) 

step  2 : 
	 In file  lib/kui/kui_term.c , function  kui_term_get_keycode_from_cgdb_key   line  440 :
 		 Return null to caller 

step  3 : 
	 In file  cgdb/interface.c , function  status_bar_regex_input   line  1007:
 		 Function kui_term_get_keycode_from_cgdb_key executes and stores the return value to keycode (keycode can be null) 

step  4 : 
	 In file  cgdb/interface.c , function  status_bar_regex_input   line  1008:
 		 key node act as 1st parameter of strlen

**Comment by brasko** [comment]
I've got 99 problems and this isn't one of them.

If anyone would like to investigate these, feel free.
