### ISSUE TITLE
Prompt line is not as wide as the terminal and wraps

### ISSUE THREAD

**Issue by auouymous** [cgdb/cgdb#275]
Typing or pasting text causes the cursor to wrap over the prompt. The actual point it wraps is around 50% of the terminal width, but it varies.

Originally reported in https://github.com/cgdb/cgdb/issues/256#issuecomment-904317189.

Wide gdb prompts (example in https://github.com/cgdb/cgdb/issues/265#issuecomment-908875699) can cause wrapping before anything has been typed.

**Comment by auouymous** [comment]
Notice how the `89` and cursor wraps around over the GDB prompt.

![cgdb-prompt-wrap](https://user-images.githubusercontent.com/5005204/136870737-95ae6e90-5ef1-4370-a190-14b74e9062c7.png)

**Comment by brasko** [comment]
OK. That is whacky. However, I also see that same bad behavior using gdb without cgdb. Can you confirm if you see this with gdb only as well? If so, it's a bug for gdb and gdb/readline.

**Comment by auouymous** [comment]
Ah, I do get the same issue in GDB.
