### ISSUE TITLE
segmentation fault when source window size exceeds length of displayed source file

### ISSUE THREAD

**Issue by frankdeath** [cgdb/cgdb#28]
cgdb segmentation faults when the source window size exceeds the length of the displayed source file.  The seg fault has been reproduced on linux (RHEL6) and OS X (10.6.8). 

Backtrace from a core dump when the size of the source window is increased by typing "=":

(gdb) bt
#0  0x0000003a406480ac in vfprintf () from /lib64/libc.so.6
#1  0x0000003a406ffa80 in __vsnprintf_chk () from /lib64/libc.so.6
#2  0x0000003a52015c99 in _nc_printf_string () from /lib64/libncurses.so.5
#3  0x0000003a5201159f in vwprintw () from /lib64/libncurses.so.5
#4  0x0000003a520117a8 in wprintw () from /lib64/libncurses.so.5
#5  0x000000000040d71f in source_display (sview=0x127c450, focus=1) at sources.c:732
#6  0x000000000040a2ac in if_draw () at interface.c:432
#7  0x000000000040a6fe in if_layout () at interface.c:534
#8  0x000000000040bb61 in source_input (key=61) at interface.c:1066
#9  internal_if_input (key=61) at interface.c:1347
#10 0x000000000040bb78 in if_input (key=61) at interface.c:1387
#11 0x000000000040381f in user_input () at cgdb.c:842
#12 user_input_loop () at cgdb.c:893
#13 0x0000000000404ca5 in main_loop (argc=<value optimized out>, argv=<value optimized out>) at cgdb.c:1362
#14 main (argc=<value optimized out>, argv=<value optimized out>) at cgdb.c:1737

(gdb) 

Backtrace from a core dump when the terminal running cgdb is resized:

(gdb) bt
#0  0x0000003a406480ac in vfprintf () from /lib64/libc.so.6
#1  0x0000003a406ffa80 in __vsnprintf_chk () from /lib64/libc.so.6
#2  0x0000003a52015c99 in _nc_printf_string () from /lib64/libncurses.so.5
#3  0x0000003a5201159f in vwprintw () from /lib64/libncurses.so.5
#4  0x0000003a520117a8 in wprintw () from /lib64/libncurses.so.5
#5  0x000000000040d71f in source_display (sview=0x17d3530, focus=0) at sources.c:732
#6  0x000000000040a2ac in if_draw () at interface.c:432
#7  0x000000000040a6fe in if_layout () at interface.c:534
#8  0x000000000040ae51 in if_resize () at interface.c:553
#9  if_resize_term () at interface.c:573
#10 0x0000000000404ba9 in cgdb_resize_term (argc=<value optimized out>, argv=<value optimized out>) at cgdb.c:1274
#11 main_loop (argc=<value optimized out>, argv=<value optimized out>) at cgdb.c:1405
#12 main (argc=<value optimized out>, argv=<value optimized out>) at cgdb.c:1737

(gdb)

**Comment by mikesart** [comment]
Closing really old issues. Please open a new bug if this problem still exists. Thanks.
