### ISSUE TITLE
Search in the file/code window has stopped working

### ISSUE THREAD

**Issue by ahlstromcj** [cgdb/cgdb#282]
Previously, I could ESCape into the top window, use "o" to search for and open a source-code file using the "/" key.  Then, in the loaded code, I could search for text using the "/" key.  The search for a file still works, but the search for text does nothing.  This is in cgdb built from code dated (in "git log") Oct 15, commit 3f35f7d on Ubuntu 20.04.3 LTS.  Currently, I have to open the file in vim and get the line number of the text I am searching.  (Also, after entering text, all that "n" does is move to the next line in the source code.)

**Comment by brasko** [comment]
Thanks! I've reproduced this. I should have a fix shortly.

**Comment by brasko** [comment]
This should be fixed. Thanks for reporting this!
