### ISSUE TITLE
Can't quit cgdb when debugging forking program

### ISSUE THREAD

**Issue by meator** [cgdb/cgdb#298]
Hello. I can't quit cgdb when I'm debugging a program that uses `fork()`. I have compiled cgdb manually with the most recent commit. My system is up to date. I'm using the glibc variant of Voidlinux.
# How to reproduce
*Paths are relative to the cloned cgdb repo.*
1. clone cgdb
2. run `./autogen.sh`
3. run `./configure`
4. run `make`
5. compile the following program with `gcc -ggdb`:
```c
#include <unistd.h>

int main()
{
	fork();
	pause();
	return 0;
}
```
6. run the compiled cgdb with `./cgdb/cgdb -- -nx <path to compiled program>` (I'm using `-nx` to make sure that this problem isn't caused by my custom gdb configuration)
7. type `break 6`
8. type `run`
9. type `quit`
10. type `y` to make cgdb quit even when the program is still running
11. cgdb is now freezed

The following steps don't cause a freeze when plain gdb is used.

Here is a [Dockerfile](https://github.com/cgdb/cgdb/files/7739993/Dockerfile.txt) that can reproduce the issue. You can reproduce the issue by running this container with `-t -i` and by following the steps 7 to 11.

**Comment by brasko** [comment]
I really wasn't expecting to reproduce this. However I did first try! I'll get a fix soon I hope.

**Comment by brasko** [comment]
OK. This took me a while to figure out.

GDB starts above program. Then the above program starts itself.
When you quit gdb it kills the top level program, but the grandchild stays alive.

CGDB doesn't properly recognize the sigchild that occurs when gdb dies.
I'll have CGDB exit when gdb dies.
However, you'll still have the grandchild running in your example. Is that OK?

**Comment by brasko** [comment]
I just pushed a fix. Please reopen the case if it's not working properly for you.

**Comment by meator** [comment]
It's working now. Thanks!
