### ISSUE TITLE
Stepping into a function shows parameters as uninitialized

### ISSUE THREAD

**Issue by ahlstromcj** [cgdb/cgdb#301]
Previously in cgdb, when one stepped into a function, the function parameters' values would be shown.  Now, uninitialized values are shown.  One has to step one more time and then display the parameter values again.  This is especially problematic with parameters that are string references, as cgdb displays a bunch of random bytes from the uninitialized string reference, and sometimes takes a painfully long time to gather the string bytes to show in the pager.

        bool myclass::myfunction (const std::string & errmessage)
A    -->{
B    -->    first_line_of_code();
            . .
        }

A: errmessage=<error reading variable: Cannot access memory at address 0xe>
B: Can now print errmessage with the "p" command.

It also seems like the call-stack "pointer" might be off, as sometimes the message refers to an earlier function that was called.

**Comment by brasko** [comment]
I could be wrong, but i think this is a bug you would want to file with gdb itself. CGDB is just the curses front end.
Please reopen the case if I've got this wrong.

**Comment by auouymous** [comment]
I can see the parameter values when breaking on functions and can print them out. Maybe your current version of gdb has a bug that has since been fixed in my newer version. Or maybe it doesn't work as well with C++ functions. Does it show argc if you break on `main` like below?

```
GNU gdb (Gentoo 11.1 vanilla) 11.1

Breakpoint 1, main (argc=1, argv=0xbfffe864) at mblen.c:110

|gdb|main|> p argc
$1 = 1
```

**Comment by ahlstromcj** [comment]
I built gdb 11 from source to replace Ubuntu's gdb 9 and behavior is much better.  Thanks!
