### ISSUE TITLE
Streamline and document pager configuration

### ISSUE THREAD

**Issue by ahlstromcj** [cgdb/cgdb#302]
This feature is nice:

    Type <RET> for more, q to quit, c to continue without paging--

However, having to hit q <enter> or c <enter> is annoying.  Would be cool to be able to just hit the q or c key and get the response immediately.

Also, can this prompt be disabled in a cgdb configuration file?

Thanks for providing updates to cgdb!  I had thought about doing that at some point, but that is a lot of work! Thank you!

**Comment by brasko** [comment]
This is also a gdb feature. However, when starting cgdb sometimes you get a prompt. You can disable this by passing -q to gdb on startup. Something like cgdb ./main -q would work.

**Comment by ahlstromcj** [comment]
I built gdb 11 from source to replace Ubuntu's gdb 9 and behavior is much better.  Thanks!
