### ISSUE TITLE
Excuse me, how to disable the following function

### ISSUE THREAD

**Issue by puppetpyt** [cgdb/cgdb#307]
While the user is debugging, via next and step, CGDB will update the source file and line number to keep you informed as to where GDB is debugging.

When using cgdb, the window of the source code has already indicated me the current information, I don't need to display the corresponding information when single step, and this will affect the speed of continuously next.

I looked for the official documentation, but I can't seem to find the corresponding way

![image](https://user-images.githubusercontent.com/33108988/151328843-bc97daff-a1b4-4d53-8a9c-f469e6cb8ebc.png)

**Comment by brasko** [comment]
This is a bug in gdb. It should be fixed upstream in gdb.
  https://sourceware.org/pipermail/gdb/2021-March/049270.html
A fix would have to be made in gdb and I currently don't have the time to do that.
