### ISSUE TITLE
Breakpoints with multiple-symbols set to ask stopped working

### ISSUE THREAD

**Issue by dflogeras** [cgdb/cgdb#311]
I sometimes end up debugging projects (like library code) with a layout like this:
src/someclass.cpp
src/someotherclass.cpp
src/....

And corresponding same-named unit tests like:
src/test/someclass.cpp
src/test/someotherclass.cpp
srt/test/....

Just hitting the spacebarin cgdb to set a breakpoint might be ambiguous and GDB's default is to set in both files of the same name.  You can override this in .gdbinit with "set multiple-symbols ask", in which GDB will ask for clarification.

I'm 99% sure this feature worked seamlessly when using cgdb in 0.7.1, however it seems it no longer does.  If I explicitly type "break filename.cpp:12" it will ask as expected, but you then lose the convenience of hitting spacebar in the UI.

**Comment by brasko** [comment]
I might need a little bit more information to try to dup the bug you have. I just setup a small example like this,
foo/file.c
bar/file.c
main.c
Then I linked them together like this,
gcc -g -c foo/file.c -o foo/file.o
gcc -g -c bar/file.c -o bar/file.o
gcc -g -o main main.c foo/file.o bar/file.o

$ cat foo/file.c
#include <stdio.h>
#include "file.h"

void foo_file()
{
    printf("In foo_file\n");
}

$ cat bar/file.c
#include <stdio.h>
#include "file.h"

void bar_file()
{
    printf("In bar_file\n");
}

Then I ran cgdb on main. I opened the file foo/file.c.

I set a breakpoint with the space bar on line 6.
4│ void foo_file()
5│ {
6│     printf("In foo_file\n");
7│ }

CGDB successfully set a breakpoint on line 6. It also set one in bar/file.c which I view as a bug.
(gdb) info breakpoints
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   <MULTIPLE>
1.1                         y   0x0000000000400549 in foo_file at foo/file.c:6
1.2                         y   0x000000000040055a in bar_file at bar/file.c:6

I'm going to look into merging the following pull request now, https://github.com/cgdb/cgdb/pull/277

However. I don't yet think i've reproduced or understood your issue. Can you clarify further?

**Comment by brasko** [comment]
I just integrated the following change into master,
  * When selecting breakpoints with the space bar in the source viewer,
    CGDB now selects breakpoints using an absolute path to the file
    instead of a relative path. This prevents breakpoints being set on files
    with the same base name.
Will this make the issue that you ran into better or worse?

**Comment by dflogeras** [comment]
This makes it work perfectly for me, thank you!
