### ISSUE TITLE
cgdb should use full path for breakpoint when pressing space

### ISSUE THREAD

**Issue by leissa** [cgdb/cgdb#313]
When you press space, cgdb will automatically set a breakpoint in the current line of the current file. However, if your project has two files with the same name in different directories, it's more or less random whether the breakpoint ends up in the correct file. Using the full name should fix this issue.

**Comment by brasko** [comment]
This was actually the last bug fixed in git.

See the NEWS file,
  * When selecting breakpoints with the space bar in the source viewer,
    CGDB now selects breakpoints using an absolute path to the file
    instead of a relative path. This prevents breakpoints being set on files
    with the same base name.

Let me know if it's not fixed and i'll reopen this case.
