### ISSUE TITLE
[feature] Can cgdb delete mark?

### ISSUE THREAD

**Issue by Freed-Wu** [cgdb/cgdb#319]
Now we can use `ma` mark a line as `a`. However, how to delete this mark?

And if we `ma`, `ms` in a same line, it will only display `a` not `s`. Maybe display the latter will be better?

Thanks.

**Comment by gahr** [comment]
So, my the suggestion would be to

1. introduce the possibility to explicitely delete a mark
2. delete the previous mark when setting a new mark over a previous one, i.e., introduce the possibility to change the letter of a mark

If @brasko is ok with this, I'll implement it.

**Comment by gahr** [comment]
Alternative
2. keep the old and the new mark when setting a new mark over a previous one (like vim does), and show the most recently set one (like the vim-showmarks plugin does)

**Comment by gahr** [comment]
@mikesart what would be your preference?

**Comment by mikesart** [comment]
I'm with @gahr - I think his alternative 2 is the one closest to vim from what I can tell. Thanks!

**Comment by brasko** [comment]
This issue should be resolved in master. Reopen if that's not the case. Thanks!
