### ISSUE TITLE
Question: How to clear search highlights

### ISSUE THREAD

**Issue by shahab-vahedi** [cgdb/cgdb#327]
I apologise if I am abusing the issue reporting for casting a question, but this one is really bugging me (pun intended).

TL;DR; How can one turn off the search highlights when they are not needed anymore? Please don't confuse it with `set nohlsearch`.

I am using the master version of `cgdb` and have the `hlsearch` set. Whenever I am done searching for a keyword, I have to still face its highlight occurrences throughout the windows. I've tried many things including reading the `cgdb.txt` and the [issues](https://github.com/cgdb/cgdb/issues) to no avail.

**Comment by brasko** [comment]
I clear it the same way as you, by any empty search. Seems sort of silly.
Do you have any suggestions? How do vim users normally do this? (I usually empty search in vim as well)

**Comment by iandinwoodie** [comment]
In Vim you can do `:noh`, which is shorthand for `:nohlsearch`, to clear the highlighting until the next search. 

Note that this is different from `:set nohlsearch` which will disable search highlighting for the session unless it is manually enabled again.

**Comment by brasko** [comment]
I agree with @iandinwoodie that :noh is the way to go. Thanks for the suggestion Ian.
In the meantime, i've implemented a small work around.
If you search for something that doesn't exist, say /zzz, then the previous search results are cleared.
This is how vim also appears to work, so it's a minor improvement in cgdb.

**Comment by brasko** [comment]
I've implemented the noh feature to the best of my ability. I'm going to close this case. Please let me know if you have any further questions.
