### ISSUE TITLE
Color prompt support

### ISSUE THREAD

**Issue by gpakosz** [cgdb/cgdb#33]
Hello,

It would be nice if `cgdb` supported color prompt. Currently, I'm having:

![](http://s24.postimg.org/am8s1d611/Screen_Shot_2013_10_24_at_9_15_32_PM.png)

**Comment by zed0** [comment]
I believe that the CGDB devs are currently looking at implementing proper support for this, however for the time being I've written a hacky patch: https://github.com/zed0/cgdb/commit/b0bd82e4cb6760e37c92bd274f7aab6c7709f8fb
It's likely to be extremely buggy, but it should give you both colors in your prompt and parse the colors in output from programs that may be running.

**Comment by krf** [comment]
Would love to see that in mainline :\

**Comment by brasko** [comment]
Thanks to Michael Sartain this has been implemented in master.

A release will probably be done in a month or two with this feature.

**Comment by krf** [comment]
For the record: https://github.com/cgdb/cgdb/commit/3d63a4bbe56e552a7d3eaf63bf430e64fc6e3baf
