### ISSUE TITLE
file dialog freezing terminal in msys2/WSL

### ISSUE THREAD

**Issue by arturfabriciohahaedgy** [cgdb/cgdb#332]
At work I'm forced to use Windows machines and so I usually stay on **msys2 terminal** or **wsl2**.

Using the standard breakpoints on GDB mode works fine but I'd like to put them in an more interactive and visual way, and in the [documentation](https://cgdb.github.io/docs/cgdb.html#Summary) it talks about a [file dialog window](https://cgdb.github.io/docs/cgdb.html#File-Dialog-Window) which, from what I gathered would let me do just that.

Unfortunately when I try to access it using msys2 or WSL the terminal just freezes and doesn't do anything nor seems to react to my input, although weirdly enough, when I try to `C-c` it, the GDB window prints a `(Quit)` on it.

![image](https://user-images.githubusercontent.com/69261664/192787757-a2348e86-29ef-41e5-998a-af34a277f84b.png)
↑ Frozen CGDB screen with `C-c` pressed a couple of times to show the behavior I'm talking about.

Would like to know if this is a bug or I'm just missing something...

OBSERVATION: I didn't try using it on my Linux machine yet, so I don't know if it's a problem that only happens on Windows.

**Comment by brasko** [comment]
Which version of cgdb are you using?
Can you send in the logs?

Thanks,
Bob Rossi

**Comment by arturfabriciohahaedgy** [comment]
Hi, sorry for the late reply!

Unfortunately I don't have access to the machine that was running cgdb anymore, so I won't be able to send any logs or give any useful information, I guess the issue could be closed by now...
