### ISSUE TITLE
cgdb bug: remote connect to kdb cannot do twice

### ISSUE THREAD

**Issue by hahaleyile** [cgdb/cgdb#334]
I was debugging a kernel module, and I find that when I remote connect to a kdb, then detach, then I can't do remote connect again. cgdb will immediately exit without any prompt. GDB don't have this problem. Thank you!

**Comment by brasko** [comment]
Any chance you have a simple duplication script?

**Comment by hahaleyile** [comment]
Sorry due to I delete the kernel object file, I cannot redo the actions describe above.
However, I am pretty sure that the config file is very common:

![image](https://user-images.githubusercontent.com/38727644/226913964-f7113c45-9c1d-4d32-be8c-01066cf432bd.png)

I am debugging a kernel module, use these commands when using cgdb:

`
cgdb vmlinux
lx-symbols
target remote udp:192.168.145.133:31337
`
Then I do detach, and cannot connect remote again. GDB has no problem.

**Comment by brasko** [comment]
I'm not sure i can do much with this bug report without more detail.
Please share me the commands that work with gdb and then the commands that do not work with cgdb.
I appreciate it. If you send that in, i'll reopen this case.
