### ISSUE TITLE
ESCape key mixup with readline

### ISSUE THREAD

**Issue by vlachoudis** [cgdb/cgdb#335]
When setting the readline to vi-mode, the escape should switch to normal mode for editing the input line.
However ESC is used by **cgdb** to send the focus to the source code window.
Is there a way to remap this feature, use a different key to jump to the source code window and leave ESCape to be handled by readline?

In some cases (I could not find a pattern) hitting ESCape doesn't jump to the source window but goes to the normal editing mode of the input line.

**Comment by vlachoudis** [comment]
Sorry I found it cgdbmodekey :)

**Comment by brasko** [comment]
I'm closing this issue as you found the work around. Let me know if you would like to reopen it.
