### ISSUE TITLE
how to disable source code display in cgdb windows

### ISSUE THREAD

**Issue by cherrylzhao** [cgdb/cgdb#336]
hi, all

I have installed cgdb-0.8.0 based on gdb-11.2, but original source of gdb will display like that:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/8317649/200995828-2889acc2-5950-4aee-bb73-68cfce6d1764.png">

how can I disable the source code display of gdb-11.2, it's ok for me when I used to gdb-7

**Comment by brasko** [comment]
Its how GDB works now unfortunately. Many cgdb users have been unhappy
about this.

If you feel inclined, you could email the gdb group and ask that this
source printing be disabled or optional in the future.

**Comment by cherrylzhao** [comment]
thanks for reply !

**Comment by brasko** [comment]
Please note this is a duplicate to https://github.com/cgdb/cgdb/issues/223.
I've submitted a patch to gdb that might help resolve this, lets see what they say.
  https://sourceware.org/pipermail/gdb/2024-May/051339.html
