### ISSUE TITLE
utf support

### ISSUE THREAD

**Issue by empty9mar** [cgdb/cgdb#342]
7bbd997 breaks utf support completely, returning back to 8029142 make it works:
$cat test.cpp
#include <iostream>
int main() {
    std::cout << "тест" << std::endl;
}
$g++ -g test.cpp -o test
$cgdb test
4│     std::cout << " ~B   ~A ~B" << std::endl;
(gdb) start
4           std::cout << "    " << std::endl;

**Comment by brasko** [comment]
@empty9mar Thanks! Will look into this.

**Comment by empty9mar** [comment]
@brasko fix works for me. Thank you.
