### ISSUE TITLE
REG 7bbd997: Multi-character input sequences are broken

### ISSUE THREAD

**Issue by ibuclaw** [cgdb/cgdb#347]
As of 7bbd997, it's no longer possible to type in multi-character sequences into cgdb (i.e: Ctrl+Left)

Before the change (as of 8029142):
```
Breakpoint 1, kui_tree::get_data (this=0x5594f3cae7e0) at ../../../lib/kui/kui_tree.cpp:145
145         return found ? found_node->macro_value : nullptr;
(gdb) p *found_node->macro_value
$1 = {original_key = 0x5594f3cd7d40 "\033[1;5D", literal_key = 0x5594f3cd8380,
  original_value = 0x5594f3cd8340 "<BACKWARD-WORD>", literal_value = 0x5594f3cd83b0}
```

After the change (as of 7bbd997):
```
Breakpoint 1, kui_tree::get_data (this=0x56444c2d2f20) at ../../../lib/kui/kui_tree.cpp:145
145         return found ? found_node->macro_value : nullptr;
(gdb) p *found_node->macro_value
$1 = {original_key = 0x56444c2dd5a0 "\033", literal_key = 0x56444c2dd340,
  original_value = 0x56444c2dd0e0 "<Esc>", literal_value = 0x56444c2dd800}
```

**Comment by ibuclaw** [comment]
@gahr - When testing use `Ctrl+Left` or `Ctrl+Right` arrow sequences.  Expected behaviour is that the cursor jumps between words on the prompt.

**Comment by gahr** [comment]
it's weird, on my macOS, option-left and option-right do move the cursor left and right one word at a time.

**Comment by ibuclaw** [comment]
> it's weird, on my macOS, option-left and option-right do move the cursor left and right one word at a time.

What's the key sequence emitted for optiot-luft/right on macOS, half expecting it not to be `\033[1;5C` or `\033[1;5D`.

I wonder if the version of readline might have an effect as well.

**Comment by brasko** [comment]
@ibuclaw Sorry this took so long to get to. However, i did just reproduce what you've seen. I'll either back out the changes that caused the issue today or see if i can resolve what the root cause is.
