### ISSUE TITLE
[bug] valgrind cannot display message

### ISSUE THREAD

**Issue by Freed-Wu** [cgdb/cgdb#352]
```c
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

char *bin_to_str(uint8_t const *bin, size_t size) {
  char *str = malloc(size * 3 + 1);
  char *p = str;
  for (int i = 0; i < size; i++) {
    sprintf(p, "%02x ", bin[i]);
    p += 3;
  }
  return str;
}

int main(int argc, char *argv[]) {
  uint8_t *bin = malloc(4);
  int fd = open("wrong.txt", O_RDONLY);
  read(fd, bin, 4);
  char *str = bin_to_str(bin, 4);
  printf("%s\n", str);
  free(str);
  return EXIT_SUCCESS;
}
```

```sh
cc -g main.c -o main
valgrind --vgdb-error=0 ./main
```

In another tty:

### Actual Behaviour

```sh
cgdb -- --ex 'target remote | vgdb'
```

```gdb
monitor help
```

Nothing will be displayed:

![Screenshot from 2024-01-11 15-13-32](https://github.com/cgdb/cgdb/assets/32936898/c8053302-ccd9-41f4-a52c-8a6ff32c017a)

### Expected Behaviour

```sh
gdb --ex 'target remote | vgdb'
```

```gdb
monitor help
```

![Screenshot from 2024-01-11 15-14-04](https://github.com/cgdb/cgdb/assets/32936898/d04e838c-9b25-486b-8685-6ce827b54cef)

```
❯ valgrind --version
valgrind-3.22.0
❯ cgdb --version
CGDB 0.8.0
Copyright 2002-2022 Bob Rossi and Mike Mueller.
CGDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
There is absolutely no warranty for CGDB.
❯ uname -r
6.6.8
```

**Comment by brasko** [comment]
@Freed-Wu Thanks for the great issue report. It was easy to reproduce the issue. I spent a little time on this today and was able to get cgdb to display the monitor help command properly. However, it still is not properly showing the gdb prompt after the command, so i've got to put a little more effort into this.

This is the first time i've had cgdb attempt to work with a gdb target. So i think that's more the issue than anything.

**Comment by brasko** [comment]
I've asked a question on the gdb mailing list regarding this,
https://sourceware.org/pipermail/gdb/2024-May/051335.html

**Comment by brasko** [comment]
This should be fixed now. Please give it a try and let me know. I'll close the issue once you confirm.
