### ISSUE TITLE
.gdbinit breakpoints executed but not shown on GUI

### ISSUE THREAD

**Issue by amireldor** [cgdb/cgdb#37]
When you set a breakpoint, the line number on the cgdb GUI turns red.

I set a breakpoint and saved it using "save breakpoints .gdbinit". `.gdbinit` is executed automatically by gdb on startup to restore a previous debugging 'session'.  Upon starting cgdb, the gdb prompt at the bottom reports that the breakpoint from .gdbinit has been set, but the GUI is not updated as if no breakpoint is set.

Typing any command (or even just an empty one) at the gdb prompt will update the GUI view at the top, reavling the magnificent breakpoint in its red glory.

**Comment by mikesart** [comment]
start_gdb() in cgdb.cpp does the following:
```
tgdb_initialize() ...
tgdb_request_current_location()...
```
tgdb_initialize winds up calling down into a2_initialize(), which does:
```
commands_issue_command( .... ANNOTATE_INFO_BREAKPOINTS .... )
```

When process_commands() gets the TGDB_UPDATE_BREAKPOINTS response, it's before the TGDB_UPDATE_FILE_POSITION response comes in, so we don't have any source information yet and the breakpoint info is dropped.

I added a a2_get_current_location() call right before the INFO_BREAKPOINTS call in a2_initialize and it fixed the issue, but I'm not sure it's the best fix. Need to have Bob review this one...

```
diff --git a/lib/tgdb/annotate-two/a2-tgdb.cpp b/lib/tgdb/annotate-two/a2-tgdb.cpp
index 76bca13..7e2c17a 100644
--- a/lib/tgdb/annotate-two/a2-tgdb.cpp
+++ b/lib/tgdb/annotate-two/a2-tgdb.cpp
@@ -220,6 +220,12 @@ int a2_initialize(void *ctx,
 
     a2_open_new_tty(a2, inferior_stdin, inferior_stdout);
 
+    /* Need to get source information before breakpoint information otherwise
+     * the TGDB_UPDATE_BREAKPOINTS event will be ignored in process_commands()
+     * because there are no source files to add the breakpoints to.
+     */
+    a2_get_current_location(a2, 1);
+
     /* gdb may already have some breakpoints when it starts. This could happen
      * if the user puts breakpoints in there .gdbinit.
      * This makes sure that TGDB asks for the breakpoints on start up.

```

**Comment by brasko** [comment]
Thanks to Michael Sartain, this has been fixed in master.

A release will most likely be done in a month or two.
