### ISSUE TITLE
Add arrow to improve visibility for SelectedLineNr

### ISSUE THREAD

**Issue by Wyatts** [cgdb/cgdb#38]
I would like to recommend adding something arrow similar to the arrow seen on the current execution line.

Currently, the highlighting for the selected group defaults to using A_BOLD with normal text which I find leads to contrast problems on several display/terminal combinations I've tested (including my workstation at work) because \033[0;37m and \033[1;37m aren't sufficiently different to be obvious in the presence of other visual noise (e.g. syntax-highlighted code).  Moreover, when your current line number has any other highlighting style (like a breakpoint), the indication of your current line disappears.

Another possibility I considered was changing the default colour to cyan (\033[0;36m) or magenta (\033[1;35m), but this doesn't work for monochrome terminals or address the alternate styling issue, so the arrow seems like an adequate compromise.  On the topic of monochrome mode, it's probably worthwhile to differentiate them by using different characters.  Maybe use the ACS_DIAMOND, ACS_BULLET, or 187|A_ALTCHARSET?

(Note: I haven't used cgdb with a light background; things may be different there.)

**Comment by brasko** [comment]
Thanks, this has been improved in master.

Now you can configure the currently executing and currently selected lines independently.

The currently executing line is drawn with a long arrow by default.
The currently selected line has a block cursor next to it.
Both are configurable to either long arrow, short arrow, highlight or block.

**Comment by Wyatts** [comment]
Great, thanks!
