### ISSUE TITLE
SelectedLineNr default style is not distinguishable on some terminals

### ISSUE THREAD

**Issue by mmueller** [cgdb/cgdb#50]
SelectedLineNr defaults to being a bold white, which looks very similar (if not identical) to the other non-selected lines in the window (which are non-bold white). We should probably choose a more distinct default style for this element.

**Comment by brasko** [comment]
This should be resolved now that the currently executing line defaults to a long arrow and the currently selected lines shows a block cursor next to it. This is in master.
