### ISSUE TITLE
Colored output of the terminal program is displayed without color, with control sequences visible

### ISSUE THREAD

**Issue by yurivict** [cgdb/cgdb#51]
I have a terminal program that senses if the standard output is a terminal (based on isatty(1)), and automatically prints control sequences when it is a terminal.

The problem is that when run under cgdb, for some reason, isatty(1) returns 'true', but output isn't printed as colored, and control sequences are printed as clear text.
When run under just gdb, output is colored.

This test case demonstrates this problem:

```
#include <unistd.h>
#include <stdio.h>

main() {
  if (isatty(1)) {
    printf("\033\[31mWe are on the terminal, this is a red text\033\[m\n");
  } else {
    printf("We are not on the terminal, this is a black text\n");
  }
}
```

I run on kde4 konsole terminal, if this matters, on FreeBSD 9.

**Comment by crowell** [comment]
this is still an issue, is there a reason this is closed?

the problem is with `scr_add` in `scroller.c`, I'd be interested in tackling this.

**Comment by yurivict** [comment]
I think this is still a problem.
