### ISSUE TITLE
cgdb is not working with the color setting in ~/.gdbinit

### ISSUE THREAD

**Issue by c02y** [cgdb/cgdb#55]
I tried two color setting for ~/.gdbinit
1. https://github.com/gdbinit/Gdbinit
2. https://github.com/longld/peda

They both add advanced features for default gdb using ~/.gdbinit file, one of them is color/highlight and they are both OK under `gdb` but not `cgdb`.

The promopt characters of "(gdb)" and other color settings in cgdb would be something like "[31mgdb$ [0m" not the colors, so, it would be a good idea to add the feature to parse these color settings for cgdb.

**Comment by brasko** [comment]
The color prompt should work in cgdb master/ now.

**Comment by c02y** [comment]
Compile failed:

    scroller.cpp:81:24: error: variable-sized object ‘rv’ may not be initialized
     char rv[length] = {};
                        ^
    make[2]: *** [scroller.o] Error 1


FYI:
Ubuntu 14.04 32-bit
GNU make v3.81
g++ v4.8.4

**Comment by brasko** [comment]
I'll modify the code to NULL it out the longer way. Hopefully will push the changes tonight.
