### ISSUE TITLE
'layout' command breaks cgdb

### ISSUE THREAD

**Issue by fabioperez** [cgdb/cgdb#57]
When I try to use the command `layout <some layout>`, the cgdb behaves oddly. I could not even quit cgdb.

![cgdb](https://cloud.githubusercontent.com/assets/294960/5666498/202f91dc-9747-11e4-8b29-976189ad921c.png)

**Comment by reisgabrieljoao** [comment]
I'm having the same issue with CGDB 0.6.5 on Ubuntu 12.04 however, I'm not sure if different layout are supposed to be supported as they are TUI specific commands.

**Comment by crowell** [comment]
@fabioperez this is due to the scroller being unable to parse non-ascii stuff.

**Comment by scottlu** [comment]
This puts gdb into TUI mode which CGDB isn't compatible with. This is a duplicate of #73.

**Comment by brasko** [comment]
Thanks to Michael Sartain there is a black list of commands now in cgdb that the user is no longer allowed to run. This prevents the behavior you found. These changes are in master.
