### ISSUE TITLE
Homebrew version (0.6.7) is outdated

### ISSUE THREAD

**Issue by hlin117** [cgdb/cgdb#58]
Homebrew has the 0.6.7 release, but the most recent release is 0.6.8.

**Comment by oblitum** [comment]
This may be an issue for the Homebrew repository itself.

https://github.com/Homebrew/homebrew/blob/ad5d6542975a8b9f69e11c70e575cf8865c87f7d/Library/Formula/cgdb.rb

**Comment by hlin117** [comment]
I created a pull request that updates the homebrew version:

**Comment by oblitum** [comment]
@hlin117 thanks!

**Comment by hlin117** [comment]
Got the request pulled in!
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cgdb.rb
