### ISSUE TITLE
help2man required

### ISSUE THREAD

**Issue by clach04** [cgdb/cgdb#64]
https://github.com/cgdb/cgdb.github.com/blob/master/index.html indicates that readline and ncurses is required but makes no reference to help2man. If help2man is missing the build will not start.

I've not found a flag to configure that disables the check BUT there is a variable that can be set to trick configure.

```
env HAS_HELP2MAN=yes sh ./configure --prefix=/usr/local
```

Make will fail on the man pages BUT the cgdb exe/binary does get created correctly:-)

**Comment by brasko** [comment]
I've removed the user of help2man, so fixed!
