### ISSUE TITLE
No way to find next in the file dialog

### ISSUE THREAD

**Issue by davidfooks** [cgdb/cgdb#68]
I just installed CGDB 20151105 from master 3a710f9b5a915b6124274197f68467e92b547db7

In the docs it says that N or n will go forward/back in the search. This doesn't appear to work.

If I'm searching for the header file something.h but I have something.cpp somethingelse.cpp and something.h
I start the search by typing /something and it matches something.cpp
I type ESC then n and nothing happens.

How do I skip to the next match?

**Comment by mmueller** [comment]
Pressing ESC cancels the search, like in vim. You need to press Enter to complete the search, and then n/N will take you to the next/previous result, respectively.

**Comment by davidfooks** [comment]
Great that works. Cheers!
