### ISSUE TITLE
source window jump to function definition given symbol

### ISSUE THREAD

**Issue by kazzmir** [cgdb/cgdb#69]
It would be convenient if I could force the source window to jump to an arbitrary function definition given a symbol. GDB already seems to have the required source location information

```
$ info line myfunction
Line 12 of "/made/up/file.cpp"
....
```

No matter what the current view of the source window is, I would like a command that displays the code for 'myfunction'.

**Comment by brasko** [comment]
I couldn't find a gdb/mi command that would get this information. If you can find it, perhaps we can implement this command, otherwise I suppose it's out of the question. Reopen the case if you would like to continue this conversation.
