### ISSUE TITLE
Stuck in TUI

### ISSUE THREAD

**Issue by fxkr** [cgdb/cgdb#73]
I've accidentally entered TUI by typing 'wh' instead of 'where' in gdb mode.

There seems to be no way to close TUI again - the normal `C-x C-a` doesn't work. The only option seems to be to close cgdb entirely with `ESC :quit`, causing me to lose my debugging session.

Also, CGDB unhelpfully (in this case) shows TUIs terminal escape sequences in the console, so TUI doesn't even work.

Maybe cgdb could disable TUI somehow?

**Comment by brasko** [comment]
Michael sartain has implemented a black list of commands in cgdb. The common TUI commands will no longer be run, preventing the issue you are describing. This is in master.

**Comment by brasko** [comment]
On Sun, Mar 27, 2016 at 11:10:35AM -0700, Felix Kaiser wrote:
> I've accidentally entered TUI by typing 'wh' instead of 'where' in gdb mode.
> 
> There seems to be no way to close TUI again - the normal `C-x C-a` doesn't work. The only option seems to be to close cgdb entirely with `ESC :quit`, causing me to lose my debugging session.
> 
> Also, CGDB unhelpfully shows its terminal escape sequences in the console, so TUI doesn't even work.
> 
> Maybe cgdb could disable TUI somehow?

This is fixed in master. It's issue #73 on github.

Thanks,
Bob Rossi
