### ISSUE TITLE
Allow jumping to a precise line in dialog mode

### ISSUE THREAD

**Issue by bmorel** [cgdb/cgdb#78]
Everything is in title.
For now, as far as I can see, it is only possible to jump to start of file, end of file, or line containing a regex.
It would be really useful to have vi-like commands to move into the file, like 125gg to go to line 125, or 10j to move 10 lines toward eof.

**Comment by bmorel** [comment]
Here is a patch for that feature.
This patch adds a multiplier to most (I may have forgotten one) vertical move commands.

[0001-Added-multipliers-for-horizontal-moves-in-source-mod.patch.txt](https://github.com/cgdb/cgdb/files/279976/0001-Added-multipliers-for-horizontal-moves-in-source-mod.patch.txt)

**Comment by bmorel** [comment]
Ok, that patch introduced a bug: the first line of the screen is always highlighted, which is bad imho.

Here is a patch to fix that (you need to apply it after, obviously):

[0002-fixed-the-first-line-of-the-screen-being-always-high.patch.txt](https://github.com/cgdb/cgdb/files/280738/0002-fixed-the-first-line-of-the-screen-being-always-high.patch.txt)

Now, this patch does not fix the bug of 1st line of a file being considered to be the next to be run. I wonder if I can work around that, too...

**Comment by mikesart** [comment]
We've got a bunch of changes in our fork right now which we're currently looking at getting merged into this branch. If you're up for building / testing before that, it'd be great. They are here currently: https://github.com/scottlu/cgdb

One of the checkins adds gg, 123G, G support in the source window. Hopefully thats what you want, but if not let me know. Thanks.
