### ISSUE TITLE
Allow highlighting/underlining/whatever of full lines

### ISSUE THREAD

**Issue by bmorel** [cgdb/cgdb#79]
For now, the line on which the cursor is only have it's line number colored. When there are several indentation levels it can make it hard to see which line you are on. Currently, the only "solution" I know about is to take the mouse and select the line, so that it highlight.

The same would be useful for the next line to be executed. Plus, the arrow is nice, but it makes the code farther than start of line, which does not help the problem in my 1st paragraph.

**Comment by bmorel** [comment]
Here is a small patch implementing partially this feature.
It only apply A_REVERSE on the line being executed, and unfortunately overwrite syntax colors. Considering the fact it's very partial, the option is disabled by default, I will try to implement the syntax color support and then to allow doing the same for the line on which the cursor is, but not today.

[0001-Reverse-video-mode-for-currently-executing-line.patch.txt](https://github.com/cgdb/cgdb/files/279688/0001-Reverse-video-mode-for-currently-executing-line.patch.txt)

PS: pretty nice code. Functions are a bit long for my taste, but it's not too hard to dig.
PPS: I tried to follow as mush as possible the coding style considering what I have seen, but it is possible I made mistakes. Fix those if you want, or just point them so that I could fix them myself.

**Comment by mikesart** [comment]
jcul has a pull request which I've been using and really like:

https://github.com/cgdb/cgdb/pull/59

I've merged that into my branch and added "set arrowstyle=long" to my cgdbrc file. Works great.

**Comment by brasko** [comment]
This functionality has all been changed in master.

The currently executing line defaults to long arrow. The currently selected line defaults to block.
Both are configurable to either, long arrow, short arrow, highlight or block.

Thanks to Michael Sartain for helping out here.
