### ISSUE TITLE
Allow for a Vertical Split

### ISSUE THREAD

**Issue by jalcine** [cgdb/cgdb#8]
A option should be provided to allow for users to render the UI in a vertically split manner. This would permit for the full screen on larger monitors and make more sense on wide-screen displays.

**Comment by hlin117** [comment]
Any particular reason why this hasn't been merged to `0.6.8`?

**Comment by bl4ck5un** [comment]
Works as well. Hope it be included in the upstream soon.

**Comment by brasko** [comment]
Thanks to Michael Sartain, this has been integrated upstream. Great patch.

**Comment by nbigaouette** [comment]
For those wondering, like me, where this patch is: 4fbf3a647d8f33ff50e7180c80090f76ebb21d41 (not in v0.6.8).

**Comment by khingblue** [comment]
I guess the key to switch to Vertical Split is Ctrl-w? I tried but it is not working.

I'm using CGDB 0.6.7 on Ubuntu.

**Comment by brasko** [comment]
On Tue, Sep 13, 2016 at 05:47:15PM -0700, khingblue wrote:
> I guess the key to switch to Vertical Split is Ctrl-w? I tried but it is not working.
> 
> I'm using CGDB 0.6.7 on Ubuntu.

You have to build from source to see this. I haven't done an official
release yet. I'm hoping in the next 2 months.

**Comment by khingblue** [comment]
Thanks, it's great to see it will be in next release.

**Comment by humblehacker** [comment]
Just putting this here for posterity.  I'm the original author of this patch.  Happy to see it finally get accepted after 7 years 😄  

Thanks to @dcohenp for bringing it back from the dead.

**Comment by brasko** [comment]
Wow, was it really 7 years? That's amazing. The feature is a great idea and a real improvement to cgdb. Michael Sartain did the work to get it integrated into cgdb. The project is relatively active now, so if you have any other ideas, now could be a good time! ha.

**Comment by odiszapc** [comment]
<Ctrl-W> is worked for me. What about configuration parameter?

The following dont work:

    :set splitorientation=vertical
    :set so=vertical

Thanks!

**Comment by luisgutz** [comment]
You need to use:
:set winsplitorientation=vertical
