### ISSUE TITLE
First line of a file is always displayed as if it was executed

### ISSUE THREAD

**Issue by bmorel** [cgdb/cgdb#80]
Everything is in title.
A line should not been marked as next executed if it is wrong. In case no line in a file is the next executed one, no line should be marked as next executed at all.
I would consider this as a bug.

On the other hand, it might be useful to mark the next line to be executed of a file even if it is not the deepest one in the callstack.
For example, imagine a project with 2 files foo.c and bar.c. A debugging sessions ends with a backtrace like this:

```
0x0123456798 in bar() at ~/example/bar.c:24
0x9876543210 in foo() at ~/example/foo.c:42
```

when the displayed file is foo, the line 42 should be be marked as next executed (since it is in the callstack), and when it's bar.c which is displayed, then line 24 should be marked.
This, is a feature request linked to the bug. Now, I don't really consider this an important feature, and I don't know enough about cgdb's code to do it myself.

**Comment by mikesart** [comment]
Hi bmorel. I'm not sure what you mean by the first line is displayed as if it was executed? The code has changed significantly, could you check if it's still happening and re-open with a picture if it's still an issue? Thanks.
