### ISSUE TITLE
MacPort on El Capitan fails to kill debugging process

### ISSUE THREAD

**Issue by shanemikel** [cgdb/cgdb#82]
I've installed gdb and cgdb from MacPorts on El Capitan.  All debugging functions I've tried so far seem to work, however, the 'k' command just asks me over and over if I want to kill the debugging process.  Once I send it, cgdb won't respond to SIGINT or EOF, and the only way I've found to get out is by manually sending a SIGKILL.

In regular gdb this works fine.

I'm a newbie to OSX as well as C (and tooling), so if there's any more info I can provide, just let me know.

**Comment by brasko** [comment]
I'm closing this issue as it's old and i have no way to reproduce it. If this issue still persists, please let me know and we'll look into it before the next release.
