### ISSUE TITLE
Strange startup output

### ISSUE THREAD

**Issue by SchweinDeBurg** [cgdb/cgdb#83]
CentOS 6.8 32-bit, stock GDB version 7.2, CGDB built from master branch (0.6.7.67.ge25327c) using GCC 5.3.0. Just launch a terminal emulator (Gnome terminal or QTerminal) and see the following:

```
^[[?1034h^[[?1034hGNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6)
  pyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

BTW, if it helps - I see this partially corrupted output only under runlevel 5 (even if I switch to another console using Alt+F2 for example). Under runlevel 3 everything looks as expected.

**Comment by mikesart** [comment]
I think that escape sequence sets the 8-bit input mode. Can you track down what gdb binary or script cgdb is launching and see where that code is coming from?

http://invisible-island.net/xterm/ctlseqs/ctlseqs.html
Ps = 1 0 3 4  -> Interpret "meta" key, sets eighth bit.
          (enables the eightBitInput resource).

**Comment by mikesart** [comment]
If you're still having issues, please re-open. Thanks.
