### ISSUE TITLE
is_gdb_tui_command not handling prefixes correctly

### ISSUE THREAD

**Issue by eush77** [cgdb/cgdb#84]
The check for GDB TUI commands introduced in 6762882c does not handle command prefixes correctly:

``` gdb
(gdb) w
WARNING: Not executing GDB TUI command: w
(gdb) fo
WARNING: Not executing GDB TUI command: fo
(gdb) f
WARNING: Not executing GDB TUI command: f
(gdb) l
WARNING: Not executing GDB TUI command: l
```

The last two are especially problematic since in GDB `f` is by default an alias for `frame`, and `l` for `list`.

I dug a little bit and found that in the last case `strncasecmp("l", "la", 1)` returns 0 — seems wrong, given how `tui_commands` array mentions all the prefixes explicitly.

**Comment by mikesart** [comment]
I believe this is fixed... Thanks!
