### ISSUE TITLE
Makefile Error

### ISSUE THREAD

**Issue by hoaaoh** [cgdb/cgdb#86]
I noticed that cgdb had small updates these days, and I got errors when compiling scroll.cpp:

error: variable-sized array may not be initialized:
      char rv[length] = {}; 

I fixed that problem with changing it to char\* rv = new char[length];

However, I think there must be an appropriate compiler that solves the variable-sized array problem.

What appropriate compiler should I use when compiling, since I didn't get errors when doing autoconf?

Thank you and sorry for the disturbance.

**Comment by step-** [comment]
I solved the same error by changing that line to
`char rv[length];`
My compiler is gcc (GCC) 4.8.3

**Comment by step-** [comment]
I fetched and recompiled today's commit  eef9ebe and this error still happens. Same fix.

**Comment by honggyukim** [comment]
I see the same compilation error as below:
```
g++ -DHAVE_CONFIG_H -DPKGDATADIR=\"/home/honggyu/usr/share/cgdb\" -DTOPBUILDDIR=\"/home/honggyu/src/cgdb/honggyu/cgdb\" -I. -I..    -I../lib/adt -I../lib/kui -I../lib/rline -I../lib/util -I../lib/tgdb -I../lib/tokenizer -I/home/honggyu/usr/include  -MT scroller.o -MD -MP -MF .deps/scroller.Tpo -c -o scroller.o scroller.cpp
scroller.cpp: In function ‘char* parse(scroller*, hl_line_attr**, const char*, const char*, int, ScrInputKind)’:
scroller.cpp:77:24: error: variable-sized object ‘rv’ may not be initialized
     char rv[length] = {};
                        ^
make[2]: *** [scroller.o] Error 1
```
I think variable length array is not standard but just gcc specific syntax, it'd be better to get rid of it. Especially this syntax cannot be compiled with clang compiler, so just created a pull request #106 . Please have a look at it!

**Comment by step-** [comment]
That's right, back in September I was seeing exactly the same compilation error as yours:
```
g++ -DHAVE_CONFIG_H -DPKGDATADIR=\"/usr/local/share/cgdb\" -DTOPBUILDDIR=\"/users/step-/cgdb\" -I. -I..    -I../lib/adt -I../lib/kui -I../lib/rline -I../lib/util -I../lib/tgdb/tgdb-base -I../lib/tgdb/annotate-two -I../lib/tgdb/gdbmi -I../lib/tokenizer -g -O2 -MT scroller.o -MD -MP -MF .deps/scroller.Tpo -c -o scroller.o scroller.cpp
scroller.cpp: In function ‘char* parse(scroller*, hl_line_attr**, const char*, const char*, int, ScrInputKind)’:
scroller.cpp:81:24: error: variable-sized object ‘rv’ may not be initialized
     char rv[length] = {};
```
Your fix in pull request #106 looks good to me; `calloc` is preferred to `new` because C++ advises not to mix C dynamic allocation with C++ dynamic allocation.

**Comment by hoaaoh** [comment]
Thanks, honggyukim. Your fix in #106 looks good to me too!

**Comment by honggyukim** [comment]
Thanks for the feedback @step- and @hoaaoh. I'll just wait until it is reviewed by the code owner.

**Comment by brasko** [comment]
Thanks everyone. I just merged in this change.

**Comment by honggyukim** [comment]
@brasko Thanks for the review!
