### ISSUE TITLE
Add support for UTF-8 identifiers

### ISSUE THREAD

**Issue by elnull** [cgdb/cgdb#9]
Here's valid example in GO language with UTF-8 identifiers:

```
package main
import "fmt"

func main() {
    var пример = "aaa"
    var 世界 = "bbb"
    fmt.Println(пример, 世界)
}
```

**This is output of GDB session**

Breakpoint 1, main.main () at a.go:4
4   func main() {
(gdb) n
5       var пример = "aaa"
(gdb) n
6       var 世界 = "bbb"
(gdb) n
7       fmt.Println(пример, 世界)
(gdb) n
aaa bbb
8   }

**This is output of CGDB session**

func main() {
    var M-PM-?M-Q~@M-PM-8M-PM-<M-PM-5M-Q~@ = "aaa"
    var M-dM-8~VM-g~U~L = "bbb"
    fmt.Println(M-PM-?M-Q~@M-PM-8M-PM-<M-PM-5M-Q~@, M-dM-8~VM-g~U~L)
}

**Comment by mikesart** [comment]
I believe this was fixed. If not, please enter a new bug. Thanks!
