### ISSUE TITLE
source code compilation error

### ISSUE THREAD

**Issue by abhiravk** [cgdb/cgdb#90]
`Making all in annotate-two
make[4]: Entering directory `/root/packages/cgdb/lib/tgdb/annotate-two'
gcc -DHAVE_CONFIG_H -I. -I../../..     -g -O2 -MT gdbwire.o -MD -MP -MF .deps/gdbwire.Tpo -c -o gdbwire.o gdbwire.c
gdbwire.c:1577: error: redefinition of typedef ‘yyscan_t’
gdbwire.c:693: note: previous declaration of ‘yyscan_t’ was here
gdbwire.c:2646: error: redefinition of typedef ‘yyscan_t’
gdbwire.c:1577: note: previous declaration of ‘yyscan_t’ was here
gdbwire.c:2700: error: redefinition of typedef ‘YY_BUFFER_STATE’
gdbwire.c:1578: note: previous declaration of ‘YY_BUFFER_STATE’ was here
make[4]: *** [gdbwire.o] Error 1
make[4]: Leaving directory `/root/packages/cgdb/lib/tgdb/annotate-two'`

I was able to manually fix this error but after that another error appeared,

`make[3]: Entering directory `/root/packages/cgdb/lib/tokenizer'
/bin/sh ../../config/ylwrap rustlexer.lpp lex.yy.c rustlexer.cpp -- flex  
make[3]: *** [rustlexer.cpp] Error 1
make[3]: Leaving directory `/root/packages/cgdb/lib/tokenizer'`

**Comment by mikesart** [comment]
This file is now gone. If you're still having issues, please enter a new bug. Thanks.
