### ISSUE TITLE
garbled characters

### ISSUE THREAD

**Issue by step-** [cgdb/cgdb#91]
I compiled the latest commit eef9ebe and I get a bunch of strange characters at the end of some lines in the command window. They remind me of emacs key chords. They get in the way when I type, but other than that cgdb works well. How can I get those characters out of the way, please? Thanks.
My term is urxvt _client_

```
# urxvtc --version
urxvt: "version": unknown or malformed option.
rxvt-unicode (urxvt) v9.19 - released: 2013-10-27
options: perl,xft,styles,combining,blink,iso14755,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```

![xscreenshot-00009](https://cloud.githubusercontent.com/assets/1414102/19432994/2fb22126-945f-11e6-8f9a-5d03cf7d2718.png)

**Comment by step-** [comment]
I assume you don't see these annoying characters. Let me try to describe better what happens.
When I start typing a new line in the cgdb bottom window, as soon as I type the first space, it turns into  character sequence " M-7". If I then press the backspace key the "M-7" disappears. I can then enter another word, and when I type a space it turns into the sequence " @". If I press backspace the "@" disappears and I can continue typing, but I occasionally see extra characters that come and go inside what I'm typing. It's very annoying.
In the above screen capture you can see some "M-V@" and "@" sequences. Note that they even appear in stuff that I haven't typed, like the version message above, or when I _list the source code in the bottom window_.

**Comment by brasko** [comment]
On Wed, Jan 11, 2017 at 6:06 AM, step <notifications@github.com> wrote:

> I assume you don't see these annoying characters. Let me try to describe
> better what happens.
>
I really have no idea why you would see things like that.

Do you see them in the log files as well? If you compile master that would
be
 ~/.cgdb/logs/cgdb_gdb_io_log1.txt.
It would be interesting to see what characters show up there.

For instance, I see,
2017-01-12 21:58:04 io.cpp:136() DEBUG:GNU gdb (Ubuntu
7.11.1-0ubuntu1~16.04) 7.11.1(\r)(\n)Copyright (C) 2016 Free Software
Foundation, Inc.(\r)(\n)License GPLv3+: GNU GPL version 3 or later <
http://gnu.org/licenses/gpl.html>(\r)(\n)This is free software: you are
free to change and redistribute it.(\r)(\n)There is NO WARRANTY, to the
extent permitted by law.  Type "show copying"(\r)(\n)and "show warranty"
for details.(\r)(\n)This GDB was configured as
"x86_64-linux-gnu".(\r)(\n)Type "show configuration" for configuration
details.(\r)(\n)For bug reporting instructions, please see:(\r)(\n)<
http://www.gnu.org/software/gdb/bugs/>.(\r)(\n)

Thanks,
Bob Rossi

**Comment by step-** [comment]
Yes, I compile master. I have ~/.cgdb but no log file inside it. Specifically, how do I compile and run to see a log file inside ~/.cgdb? Note that I also do have .tgdb and an empty log file inside it.

**Comment by step-** [comment]
I removed .cgdb and .tgdb, and ran cgdb without arguments. ~/.cgdb was created empty. ./tgdb was created with log files in it. a2_tgdb_debug1.txt has text that looks very similar to your paste above. Most importantly, all lines endings are logged as "(\r)(\n)". So we know that cgdb isn't logging garbage characters, so very likely it isn't outputting them either.  However, my screen keeps showing garbage characters when I run cgdb only, other terminal programs I use never show garbage chars.

In the screenshot above, garbage in the fourth line seems to come from the tail of the third line, as if a buffer was reused and was missing a `\000' to terminate a string. Perhaps it's a problem in my ncurses library?  I should test some other program that uses ncurses the way cgdb does. Any suggestions?

I tried cgdb with urxvt, xterm and a terminal based on the vte0 library. In all cases I see the garbage characters.

Meanwhile, I'm going to pull master and recompile, since I shouldn't be getting the .tgdb folder at all, according to your comments.

**Comment by step-** [comment]
I should add that this issue _started happening_ after some major commit your team did, I don't exactly recall when, but I have some snapshots saved, so I could give a date bracket, if you think it's important.

**Comment by step-** [comment]
Good news, master 7bdf9ed shows no garbage characters.
I haven't seen a cgdb screen so clean since last summer, at least!
If you want to investigate what changed, I can tell you that commit 177e5b9 shows garbage characters here. That commit is dated 2016-12-07, 32 commits before 7bdf9ed.

**Comment by brasko** [comment]
On Fri, Jan 13, 2017 at 12:00 PM, step <notifications@github.com> wrote:

> Meanwhile, I'm going to pull master and recompile, since I shouldn't be
> getting the .tgdb folder at all, according to your comments.
>

Correct. Please try the latest master changes. Some changes have been made
that may have fixed the issue you are seeing.

Thanks,
Bob Rossi

**Comment by step-** [comment]
Fixed. Thanks.
