### ISSUE TITLE
Autocompletion on directories failes to append '/'

### ISSUE THREAD

**Issue by gahr** [cgdb/cgdb#96]
Using cgdb from trunk

configured with `--with-readline=/usr/local` (readline-6.3.8)
invoked as `cgdb -d /usr/local/bin/gdb` (gdb-7.11.1)

```
(gdb) dir /us<tab>
```

completes to ```/usr<space>```, where `<space>` is an actual space character. This means that to build a path using tab-completion one has to delete the space character, type a ```/```, then type part of the next path component. Cumbersome..

Plain gdb completes the same sequence to ```/usr/```, which allows for a faster construction of paths.

**Comment by mikesart** [comment]
This is interesting. If I use the "interpreter-exec" command, which is what cgdb uses, it returns "dir /usr\n" without the trailing slash.

```
(gdb 7.12) interpreter-exec mi "complete dir /us"
&"complete dir /us\n"
~"dir /usr\n"
^done
```

This looks like a bug with gdb and I'm not sure what we could do to workaround it.

**Comment by gahr** [comment]
True - gdb must be doing something in addition to "complete-dir". However, I still see this as a cgdb bug, as it boils down to a difference in handling tab completion:

gdb: `dir /us<tab>` --> `dir /usr/`
cgdb: `dir /us<tab>` --> `dir /usr<space>`

**Comment by brasko** [comment]
I believe this will be fixed in the new-ui branch. Please let me know. Thanks.

**Comment by gahr** [comment]
Yes, the new-ui branch works fine wrt this issue, thanks!

**Comment by brasko** [comment]
Great, i've pushed this to master. Closing as resolved.
