### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by chinaminiren** [cgdb/cgdb#98]
error info:

> tgdb.cpp:472:34: 错误：expected ‘)’ before ‘PRIx64’
     return sys_aprintf("%s *0x%" PRIx64, action, addr);

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright © 2015 Free Software Foundation, Inc.

**Comment by brasko** [comment]
If you add
#define __STDC_FORMAT_MACROS 1
to the first line in tgdb.cpp, does that solve the problem?

**Comment by longhai123** [comment]
yes,just before #include <inttypes.h>

**Comment by brasko** [comment]
I just merged this fix in.
