### ISSUE TITLE
cgdb golang support

### ISSUE THREAD

**Issue by fastfading** [cgdb/cgdb#99]
I am using golang on ubuntu x86_64
with GNU gdb (Ubuntu 7.11.90.20161005-0ubuntu1) 7.11.90.20161005-git

when I debug golang.
the src window display is right for the main package code .
But when step into other package functions,  display window shows wrong infos
like below
******************************************************************************
                                                           ool mugen)

                                          =, func .soundWrite.signature:) = "misc.so";

                                          =, func .soundWrite.signature:) = "misc.so";

                                                           ndWrite:);
                                                                 e:);

                                                           ol) bool {

                                                               ))
***********************************************************************************************************************************************
But the gdb process works right.

Can you help to fix this bugs?
Thanks a lot

**Comment by brasko** [comment]
On Mon, Dec 05, 2016 at 09:17:53PM -0800, fastfading wrote:
> Can you help to fix this bugs?

I'd be happy to help.

Can you send
 - a source file that reproduces this problem
 - the command to compile the file into an executable
 - the cgdb commands to get to the point where cgdb displays wrong

With that I can probably resolve the issue for you.

Thanks,
Bob Rossi

**Comment by fastfading** [comment]
Hi  Bob
I have change some code and the cgdb work well now.
I don't know why.
I guess there is invisible character in comments to cause this .
I will contact u once I found the same issue again.
Thank you very much.


2016-12-08 22:00 GMT+08:00 brasko <notifications@github.com>:

**Comment by brasko** [comment]
Closing issue until it can be reproduced. I'm happy to reopen and help fix at that point.
